---
apiVersion: v1
kind: Pod
metadata:
  name: mock-segment
  labels:
    app: mock-segment
spec:
  containers:
    - name: mock-segment
      image: quay.io/ansible/dummy-segment@sha256:9f8a58b56f3dc1d0fa363bd67a85e68a710819760bc56a38017c1e772c3f6a2e
      ports:
        - containerPort: 9999
      readinessProbe:
        httpGet:
          path: /health
          port: 9999
        initialDelaySeconds: 3
        periodSeconds: 2
