import { Compass, CompassContent } from '@patternfly/react-core'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

import { AlertProvider } from '../components/alerts'
import { TestSignInCallback } from '../routes/access-management/authentication/identity-providers/TestSignInCallback'
import { ColorSchemeProvider } from '../theme/ColorSchemeProvider'

import { AppDockedNav } from './AppDockedNav'
import { AppLogin } from './AppLogin'
import { AppRoute } from './AppRoute'
import { AppRouter } from './AppRouter'
import { UnsavedChangesProvider } from './UnsavedChangesProvider'

const queryClient = new QueryClient()

export default function App() {
  // Handle test-signin callback before auth — the popup doesn't need a full session.
  // A cryptographic nonce generated by the opener is verified before processing claims,
  // preventing cross-window data injection.
  if (globalThis.location.pathname === AppRoute.Auth.TestSignInCallback) {
    return <TestSignInCallback />
  }

  return (
    <QueryClientProvider client={queryClient}>
      <ColorSchemeProvider>
        <AlertProvider>
          <UnsavedChangesProvider>
            <AppLogin>
              <Compass
                className="pf-m-no-screen-warning bg-deep-space"
                dock={<AppDockedNav />}
                main={
                  <CompassContent role="main">
                    <AppRouter />
                  </CompassContent>
                }
              />
            </AppLogin>
          </UnsavedChangesProvider>
        </AlertProvider>
      </ColorSchemeProvider>
    </QueryClientProvider>
  )
}
