"""add resource_name to audit events

Revision ID: 731fabfe0830
Revises: 6a6aee0b3b0d
Create Date: 2026-05-01 10:39:05.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from nexus.core.constants import FieldLimits

# revision identifiers, used by Alembic.
revision: str = "731fabfe0830"
down_revision: str | Sequence[str] | None = "6a6aee0b3b0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_events", sa.Column("resource_name", sa.String(length=FieldLimits.NAME_MAX_LENGTH), nullable=True)
    )
    op.create_index(op.f("ix_audit_events_resource_name"), "audit_events", ["resource_name"], unique=False)
    op.create_index(
        "ix_audit_events_resource_name_created_at_id",
        "audit_events",
        ["resource_name", "created_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_events_resource_name_created_at_id", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_resource_name"), table_name="audit_events")
    op.drop_column("audit_events", "resource_name")
    # ### end Alembic commands ###
