"""Add enum types to audit_events table.

Revision ID: abc123def456
Revises: 2e0b9ae06c0a
Create Date: 2026-04-21 00:00:00.000000

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "abc123def456"
down_revision: str | Sequence[str] | None = "2e0b9ae06c0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# CUSTOM: Define PostgreSQL ENUM types for audit event fields
# Alembic autogenerate does not handle CREATE TYPE with checkfirst; we do it
# here so the migration is idempotent on re-runs and safe under concurrent startup.
# IMPORTANT: Enum values are defined in ALPHABETICAL ORDER to ensure
# PostgreSQL sorts them correctly. PostgreSQL enums sort by definition order,
# not by value, so alphabetical order here = alphabetical sort in queries.
eventcategory = postgresql.ENUM(
    "agent_interaction",
    "api_execution",
    "llm_interaction",
    "llm_reasoning",
    "llm_tool_call",
    "security_event",
    "system_operation",
    "user_action",
    "workflow_event",
    name="eventcategory",
)
eventseverity = postgresql.ENUM(
    "critical",
    "error",
    "info",
    "warning",
    name="eventseverity",
)
eventstatus = postgresql.ENUM(
    "error",
    "success",
    name="eventstatus",
)
actortype = postgresql.ENUM(
    "service",
    "system",
    "user",
    name="actortype",
)
# END CUSTOM


def upgrade() -> None:
    """Upgrade schema."""
    # CUSTOM: create enum types first (checkfirst=True makes this idempotent)
    eventcategory.create(op.get_bind(), checkfirst=True)
    eventseverity.create(op.get_bind(), checkfirst=True)
    eventstatus.create(op.get_bind(), checkfirst=True)
    actortype.create(op.get_bind(), checkfirst=True)
    # END CUSTOM

    # ### commands auto generated by Alembic - please adjust! ###
    # Alter existing string columns to use enum types
    # PostgreSQL requires using USING clause to cast existing string values
    op.execute(
        """
        ALTER TABLE audit_events
        ALTER COLUMN event_category TYPE eventcategory
        USING event_category::eventcategory
        """
    )

    op.execute(
        """
        ALTER TABLE audit_events
        ALTER COLUMN event_severity TYPE eventseverity
        USING event_severity::eventseverity
        """
    )

    # Set default for event_severity
    op.execute(
        """
        ALTER TABLE audit_events
        ALTER COLUMN event_severity SET DEFAULT 'info'::eventseverity
        """
    )

    op.execute(
        """
        ALTER TABLE audit_events
        ALTER COLUMN event_status TYPE eventstatus
        USING event_status::eventstatus
        """
    )

    op.execute(
        """
        ALTER TABLE audit_events
        ALTER COLUMN actor_type TYPE actortype
        USING actor_type::actortype
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert enum columns back to strings
    op.execute(
        """
        ALTER TABLE audit_events
        ALTER COLUMN event_category TYPE VARCHAR
        USING event_category::text
        """
    )

    op.execute(
        """
        ALTER TABLE audit_events
        ALTER COLUMN event_severity TYPE VARCHAR
        USING event_severity::text
        """
    )

    # Remove default
    op.execute(
        """
        ALTER TABLE audit_events
        ALTER COLUMN event_severity DROP DEFAULT
        """
    )

    op.execute(
        """
        ALTER TABLE audit_events
        ALTER COLUMN event_status TYPE VARCHAR
        USING event_status::text
        """
    )

    op.execute(
        """
        ALTER TABLE audit_events
        ALTER COLUMN actor_type TYPE VARCHAR
        USING actor_type::text
        """
    )
    # ### end Alembic commands ###

    # CUSTOM: drop enum types (only if not used elsewhere)
    eventcategory.drop(op.get_bind(), checkfirst=True)
    eventseverity.drop(op.get_bind(), checkfirst=True)
    eventstatus.drop(op.get_bind(), checkfirst=True)
    actortype.drop(op.get_bind(), checkfirst=True)
    # END CUSTOM
