/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/invocations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Invocations
     * @description List invocations with cursor-based pagination and filtering
     */
    get: operations['list_invocations']
    put?: never
    /**
     * Create Invocation (Async)
     * @description Accept async agent invocation request and return invocation ID immediately.
     */
    post: operations['create_invocation']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/invocations/chat': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Invocation with File Uploads (Async)
     * @description Accept async agent invocation request with optional file uploads via multipart/form-data.
     */
    post: operations['create_invocation_chat']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/invocations/{invocation_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Invocation Details (Testing/Debug)
     * @description Retrieve full invocation details including the result. NOTE: This endpoint is for testing and debugging. Production systems should use WebSockets for real-time results.
     */
    get: operations['get_invocation']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/invocations/{invocation_id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Cancel Invocation
     * @description Cancel a running or pending invocation.
     */
    post: operations['cancel_invocation']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * InvocationStatus
     * @description Status enum for invocation lifecycle.
     * @enum {string}
     */
    InvocationStatus: 'created' | 'running' | 'paused' | 'cancelled' | 'completed' | 'failed'
    /**
     * Invocation
     * @description SQLModel for async workflow invocations.
     */
    Invocation: components['schemas']['UserOwnedResource'] & {
      /**
       * Project Id
       * Format: uuid
       * @description Project namespace for resource isolation
       */
      project_id: string
      /**
       * Prompt
       * @description Natural language user request
       */
      prompt: string
      /**
       * Session Id
       * @description Session identifier for multi-tenant isolation
       */
      session_id: string
      /**
       * @description Current invocation status
       * @default created
       */
      status?: components['schemas']['InvocationStatus']
      /**
       * Model Name
       * @description LLM model name used for the invocation
       */
      model_name?: string | null
      /**
       * Started At
       * @description Timestamp when workflow execution started
       */
      started_at?: string | null
      /**
       * Completed At
       * @description Timestamp when workflow completed
       */
      completed_at?: string | null
      /**
       * Context Data
       * @description Additional context for the request, including file_ids array if files uploaded
       */
      context_data?: {
        [key: string]: unknown
      }
      /**
       * Result
       * @description Workflow result data
       */
      result?: {
        [key: string]: unknown
      } | null
      /**
       * Error Message
       * @description Error message if invocation failed
       */
      error_message?: string | null
      /**
       * Checkpoint Data
       * @description Checkpoint data for pause/resume
       */
      checkpoint_data?: {
        [key: string]: unknown
      } | null
    }
    /**
     * InvocationRequestWithFile
     * @description Multipart form body for POST /invocations/chat (file upload path).
     */
    InvocationRequestWithFile: {
      /** Prompt */
      prompt?: string | null
      /** Session Id */
      session_id?: string | null
      /** Context Data */
      context_data?: string | null
      /** Files */
      files?: string[] | null
      /** Project Id */
      project_id: string
    }
    /**
     * InvocationListResponse
     * @description Paginated list response for invocations.
     */
    InvocationListResponse: components['schemas']['ResourcesResponseBase'] & {
      resources: components['schemas']['Invocation'][]
    }
    /**
     * InvocationCreateRequest
     * @description Request schema for creating a new invocation.
     *
     *     Supports multiple field name formats:
     *     - snake_case (API contract): session_id, context_data
     *     - camelCase (backward compatibility): sessionId, contextData
     *
     *     Note: created_by is automatically set from authenticated user context.
     */
    InvocationCreateRequest: {
      /**
       * Prompt
       * @description Natural language request describing desired automation task
       */
      prompt: string
      /**
       * Sessionid
       * @description Session identifier for grouping related invocations
       */
      sessionId: string
      /**
       * Contextdata
       * @description Optional additional context for the request. Use 'file_ids' (array of UUID strings) to reference uploaded files.
       */
      contextData?: {
        [key: string]: unknown
      }
      /**
       * Projectid
       * Format: uuid
       * @description Project to associate this invocation with
       */
      projectId: string
    }
    /**
     * InvocationCancelRequest
     * @description Request schema for cancelling an invocation.
     *
     *     Supports multiple field name formats:
     *     - camelCase (API contract): reason
     *     - snake_case (internal): reason
     */
    InvocationCancelRequest: {
      /**
       * Reason
       * @description Optional reason for cancellation
       * @default User cancelled
       */
      reason?: string
    }
    /**
     * InvocationCancelResponse
     * @description Response schema for invocation cancellation.
     *
     *     Indicates whether the cancellation was successful or failed.
     */
    InvocationCancelResponse: {
      /**
       * Success
       * @description True if cancellation was successful, False otherwise
       */
      success: boolean
      /**
       * Message
       * @description Human-readable message describing the cancellation result
       */
      message: string
    }
    /**
     * Paginated Response Base
     * @description Pagination metadata structure for list responses
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    ResourcesResponseBase: {
      /**
       * Next
       * @description Cursor for next page of results
       */
      next?: string | null
      /**
       * Prev
       * @description Cursor for previous page of results
       */
      prev?: string | null
      /**
       * Total
       * @description Total count of resources (only when include_total=true)
       */
      total?: number | null
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources?: unknown[]
    }
    /**
     * Base Resource
     * @description Foundational schema for all API resources with system-managed metadata
     */
    BaseResource: {
      /**
       * Resource ID
       * Format: uuid
       * @description Unique identifier for the resource
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      readonly id?: string
      /**
       * Created At
       * Format: date-time
       * @description Timestamp when resource was created
       * @example 2025-10-09T12:00:00Z
       */
      readonly created_at?: string
      /**
       * Updated At
       * Format: date-time
       * @description Timestamp when resource was last updated
       * @example 2025-10-09T12:30:00Z
       */
      readonly updated_at?: string
      /**
       * Labels
       * @description Key-value pairs for resource labeling and filtering
       * @default {}
       * @example {
       *       "environment": "production",
       *       "region": "us-east-1",
       *       "team": "platform"
       *     }
       */
      labels?: {
        [key: string]: string
      }
    }
    UserOwnedResource: components['schemas']['BaseResource'] & {
      /**
       * Created By
       * Format: uuid
       * @description User (or automation) that created the resource
       * @example 770e8400-e29b-41d4-a716-446655440000
       */
      readonly created_by: string
      /**
       * Updated By
       * @description User (or automation) that last updated the resource
       * @example 880e8400-e29b-41d4-a716-446655440000
       */
      readonly updated_by?: string | null
    }
    /**
     * ErrorData
     * @description RFC 9457 Problem Details format for error event data.
     *     This model is used for streaming error events and follows the RFC 9457 Problem Details specification. It provides machine-readable and human-readable error information with consistent structure.
     *     Attributes:
     *         type: URI reference identifying the problem type
     *         title: Short, human-readable summary of the problem
     *         detail: Human-readable explanation specific to this occurrence
     *         code: Machine-readable error code for programmatic handling
     *         retryable: Whether this error can be retried by creating a new invocation
     *         instance: Optional URI reference identifying the specific occurrence
     * @example {
     *       "type": "https://api.nexus.com/errors/llm-error",
     *       "title": "LLM Rate Limit Exceeded",
     *       "detail": "OpenRouter API rate limit exceeded. Please try again in a few moments.",
     *       "code": "RATE_LIMIT_EXCEEDED",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     * @example {
     *       "type": "https://api.nexus.com/errors/timeout-error",
     *       "title": "Streaming Timeout",
     *       "detail": "LLM streaming timed out after 30 seconds",
     *       "code": "STREAM_TIMEOUT",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     */
    ErrorData: {
      /**
       * Type
       * @description URI reference identifying the problem type
       * @example https://api.nexus.com/errors/llm-error
       */
      type: string
      /**
       * Title
       * @description Short, human-readable summary of the problem
       * @example LLM Service Unavailable
       */
      title: string
      /**
       * Detail
       * @description Human-readable explanation specific to this occurrence
       * @example OpenRouter API returned error: rate limit exceeded. Please try again in a few moments.
       */
      detail: string
      /**
       * Code
       * @description Machine-readable error code for programmatic handling
       * @example RATE_LIMIT_EXCEEDED
       */
      code: string
      /**
       * Retryable
       * @description Whether this error can be retried by creating a new invocation
       * @example true
       */
      retryable: boolean
      /**
       * Instance
       * @description Optional URI reference identifying the specific occurrence
       * @example /invocations/550e8400-e29b-41d4-a716-446655440000
       */
      instance?: string | null
    }
  }
  responses: {
    /** @description Bad Request */
    BadRequestError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.nexus.com/errors/bad-request",
         *       "title": "Bad Request",
         *       "detail": "The request was malformed or contained invalid parameters",
         *       "code": "BAD_REQUEST",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.nexus.com/errors/unauthorized",
         *       "title": "Unauthorized",
         *       "detail": "Authentication is required to access this resource",
         *       "code": "UNAUTHORIZED",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Forbidden */
    ForbiddenError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.nexus.com/errors/forbidden",
         *       "title": "Forbidden",
         *       "detail": "You do not have permission to access this resource",
         *       "code": "FORBIDDEN",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Not Found */
    NotFoundError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.nexus.com/errors/not-found",
         *       "title": "Resource Not Found",
         *       "detail": "No resource exists with the provided identifier",
         *       "code": "NOT_FOUND",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Conflict */
    ConflictError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.nexus.com/errors/conflict",
         *       "title": "Conflict",
         *       "detail": "The request conflicts with the current state of the resource",
         *       "code": "CONFLICT",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Validation Error */
    ValidationError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.nexus.com/errors/validation-error",
         *       "title": "Validation Error",
         *       "detail": "Field 'name' must be between 1 and 255 characters",
         *       "code": "VALIDATION_ERROR",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Too Many Requests */
    RateLimitError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.nexus.com/errors/rate-limited",
         *       "title": "Too Many Requests",
         *       "detail": "Rate limit exceeded. Try again in 60 seconds.",
         *       "code": "RATE_LIMITED",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Internal Server Error */
    InternalServerError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.nexus.com/errors/internal-error",
         *       "title": "Internal Server Error",
         *       "detail": "An unexpected error occurred",
         *       "code": "INTERNAL_ERROR",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
  }
  parameters: {
    /** @description Maximum number of results per page */
    limitParam: number
    /** @description Pagination cursor from previous response */
    cursorParam: string | null
    /** @description Sort parameter (e.g., 'name', '-created_at') */
    sortParam: string | null
    /** @description Include total count in response (expensive) */
    includeTotalParam: boolean
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_invocations: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: components['parameters']['sortParam']
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
        /** @description Filter invocations by status (running, paused, cancelled, completed, failed) */
        status?: components['schemas']['InvocationStatus'] | null
        /** @description Filter by creator UUID */
        created_by?: string | null
        /** @description Filter by session ID */
        session_id?: string | null
        /** @description Filter by prompt text (substring match) */
        prompt?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of invocations */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InvocationListResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  create_invocation: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InvocationCreateRequest']
      }
    }
    responses: {
      /** @description Invocation accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Invocation']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  create_invocation_chat: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['InvocationRequestWithFile']
      }
    }
    responses: {
      /** @description Invocation accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Invocation']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  get_invocation: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description UUID of the invocation to retrieve */
        invocation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Invocation details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Invocation']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
  cancel_invocation: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description UUID of the invocation to cancel */
        invocation_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InvocationCancelRequest']
      }
    }
    responses: {
      /** @description Cancellation result */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InvocationCancelResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      429: components['responses']['RateLimitError']
      500: components['responses']['InternalServerError']
    }
  }
}
