"""integration and tool hard deletes

Replace the partial unique indexes on tools.namespaced_name and
integrations.name (scoped to non-deleted rows) with plain unique
constraints, matching the "Hard Deletes Only" decision record
(AAP-79262).

Revision ID: 0154989e046f
Revises: b294b6074183
Create Date: 2026-07-20 09:22:04.836073

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0154989e046f"
down_revision: str | Sequence[str] | None = "b294b6074183"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Remove soft-deleted tool and integration rows, swap partial unique indexes for constraints."""
    # CUSTOM: Clean up any existing soft-deleted tool rows before changing the constraint.
    # Make tool_executions.tool_id nullable first, then null out FKs in tool_executions
    # and usage_counters — the ON DELETE SET NULL cascade and nullable change are not
    # added until a later migration, so we must do both manually here.
    op.alter_column("tool_executions", "tool_id", existing_type=sa.UUID(), nullable=True)
    op.execute(
        sa.text(
            "UPDATE tool_executions SET tool_id = NULL"
            " WHERE tool_id IN (SELECT id FROM tools WHERE deleted_at IS NOT NULL)"
        )
    )
    op.execute(
        sa.text(
            "UPDATE usage_counters SET tool_id = NULL"
            " WHERE tool_id IN (SELECT id FROM tools WHERE deleted_at IS NOT NULL)"
        )
    )
    op.execute(
        sa.text("DELETE FROM tool_parameters WHERE tool_id IN (SELECT id FROM tools WHERE deleted_at IS NOT NULL)")
    )
    op.execute(sa.text("DELETE FROM tools WHERE deleted_at IS NOT NULL"))
    # END CUSTOM

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tools_namespaced_name_unique"), table_name="tools", postgresql_where="(deleted_at IS NULL)")
    op.create_unique_constraint("uq_tools_namespaced_name", "tools", ["namespaced_name"])
    # ### end Alembic commands ###

    # CUSTOM: Clean up any existing soft-deleted integration rows and their dependents.
    # Null out FKs in tool_executions and usage_counters for tools belonging to
    # soft-deleted integrations before deleting those tools.
    op.execute(
        sa.text(
            "UPDATE tool_executions SET tool_id = NULL WHERE tool_id IN ("
            "  SELECT t.id FROM tools t"
            "  JOIN integrations i ON t.integration_id = i.id"
            "  WHERE i.deleted_at IS NOT NULL"
            ")"
        )
    )
    op.execute(
        sa.text(
            "UPDATE usage_counters SET tool_id = NULL WHERE tool_id IN ("
            "  SELECT t.id FROM tools t"
            "  JOIN integrations i ON t.integration_id = i.id"
            "  WHERE i.deleted_at IS NOT NULL"
            ")"
        )
    )
    op.execute(
        sa.text(
            "DELETE FROM tool_parameters WHERE tool_id IN ("
            "  SELECT t.id FROM tools t"
            "  JOIN integrations i ON t.integration_id = i.id"
            "  WHERE i.deleted_at IS NOT NULL"
            ")"
        )
    )
    op.execute(
        sa.text("DELETE FROM tools WHERE integration_id IN (SELECT id FROM integrations WHERE deleted_at IS NOT NULL)")
    )
    op.execute(
        sa.text(
            "DELETE FROM llm_models WHERE integration_id IN ("
            "  SELECT id FROM integrations WHERE deleted_at IS NOT NULL"
            ")"
        )
    )
    op.execute(
        sa.text(
            "DELETE FROM integration_project_assignments WHERE integration_id IN ("
            "  SELECT id FROM integrations WHERE deleted_at IS NOT NULL"
            ")"
        )
    )
    op.execute(sa.text("DELETE FROM integrations WHERE deleted_at IS NOT NULL"))
    # END CUSTOM

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_integrations_name_unique"), table_name="integrations", postgresql_where="(deleted_at IS NULL)"
    )
    op.create_unique_constraint("uq_integrations_name", "integrations", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Restore the partial unique indexes (data loss from cleanup is not reversible)."""
    # CUSTOM: Revert the nullable change on tool_executions.tool_id.
    op.alter_column("tool_executions", "tool_id", existing_type=sa.UUID(), nullable=False)
    # END CUSTOM

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_integrations_name", "integrations", type_="unique")
    op.create_index(
        op.f("ix_integrations_name_unique"),
        "integrations",
        ["name"],
        unique=True,
        postgresql_where="(deleted_at IS NULL)",
    )
    op.drop_constraint("uq_tools_namespaced_name", "tools", type_="unique")
    op.create_index(
        op.f("ix_tools_namespaced_name_unique"),
        "tools",
        ["namespaced_name"],
        unique=True,
        postgresql_where="(deleted_at IS NULL)",
    )
    # ### end Alembic commands ###
