"""add integrations.last_refreshed_at index

Revision ID: 07040ea5b2d8
Revises: a9f3c7e21b04
Create Date: 2026-07-30 09:25:10.856609

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07040ea5b2d8"
down_revision: str | Sequence[str] | None = "a9f3c7e21b04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_integrations_last_refreshed_at"), "integrations", ["last_refreshed_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_integrations_last_refreshed_at"), table_name="integrations")
    # ### end Alembic commands ###
