"""add_is_builtin_to_role_assignments

Revision ID: 0d9c776ea7bb
Revises: bc6b9f994d1f
Create Date: 2026-05-11 14:46:59.375216

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d9c776ea7bb"
down_revision: str | Sequence[str] | None = "bc6b9f994d1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("role_assignments", sa.Column("is_builtin", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column("role_assignments", "is_builtin", server_default=None)
    op.create_index(op.f("ix_role_assignments_is_builtin"), "role_assignments", ["is_builtin"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_role_assignments_is_builtin"), table_name="role_assignments")
    op.drop_column("role_assignments", "is_builtin")
    # ### end Alembic commands ###
