"""add has_validation_issues to workflows

Revision ID: 12da74e24c7b
Revises: c7d8e9f01234
Create Date: 2026-06-25 12:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12da74e24c7b"
down_revision: str | Sequence[str] | None = "c7d8e9f01234"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflows",
        sa.Column("has_validation_issues", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflows", "has_validation_issues")
    # ### end Alembic commands ###
