"""Add index on file_metadata retention_expires_at.

Revision ID: 1ca21f73e381
Revises: af63ce50dceb
Create Date: 2026-06-11

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ca21f73e381"
down_revision: str | None = "dce0fe2acbec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:  # noqa: D103
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_file_metadata_retention_expires_at"), "file_metadata", ["retention_expires_at"])
    # ### end Alembic commands ###


def downgrade() -> None:  # noqa: D103
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_metadata_retention_expires_at"), table_name="file_metadata")
    # ### end Alembic commands ###
