"""add retried_from_execution_id to executions

Revision ID: 1f7811e54a52
Revises: eeb222146519
Create Date: 2026-06-29 21:30:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1f7811e54a52"
down_revision: str | Sequence[str] | None = "eeb222146519"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "executions",
        sa.Column("retried_from_execution_id", sa.Uuid(), nullable=True),
    )
    op.create_index(
        "ix_executions_retried_from_execution_id",
        "executions",
        ["retried_from_execution_id"],
    )
    op.create_foreign_key(
        "fk_executions_retried_from_execution_id",
        "executions",
        "executions",
        ["retried_from_execution_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_executions_retried_from_execution_id", "executions", type_="foreignkey")
    op.drop_index("ix_executions_retried_from_execution_id", table_name="executions")
    op.drop_column("executions", "retried_from_execution_id")
    # ### end Alembic commands ###
