"""refactor authz: remove builtin data from db, add credential_type unique constraint

Revision ID: 219dcd505ee5
Revises: be29d7c7e75f
Create Date: 2026-04-21 17:18:23.078140

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "219dcd505ee5"
down_revision: str | Sequence[str] | None = "be29d7c7e75f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_role_policies_created_at"), table_name="role_policies")
    op.drop_index(op.f("ix_role_policies_id"), table_name="role_policies")
    op.drop_index(op.f("ix_role_policies_policy_id"), table_name="role_policies")
    op.drop_index(op.f("ix_role_policies_role_id"), table_name="role_policies")
    op.drop_index(op.f("ix_role_policies_updated_at"), table_name="role_policies")
    op.drop_table("role_policies")
    op.add_column("group_role_assignments", sa.Column("role_name", sa.String(length=255), nullable=False))
    op.drop_index(op.f("ix_group_role_assignments_role_id"), table_name="group_role_assignments")
    op.drop_index(
        op.f("ix_gra_group_role_global"), table_name="group_role_assignments", postgresql_where="(project_id IS NULL)"
    )
    op.create_index(
        "ix_gra_group_role_global",
        "group_role_assignments",
        ["group_id", "role_name"],
        unique=True,
        postgresql_where=sa.text("project_id IS NULL"),
    )
    op.drop_index(
        op.f("ix_gra_group_role_project"),
        table_name="group_role_assignments",
        postgresql_where="(project_id IS NOT NULL)",
    )
    op.create_index(
        "ix_gra_group_role_project",
        "group_role_assignments",
        ["group_id", "role_name", "project_id"],
        unique=True,
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.create_index(op.f("ix_group_role_assignments_role_name"), "group_role_assignments", ["role_name"], unique=False)
    op.drop_constraint(op.f("group_role_assignments_role_id_fkey"), "group_role_assignments", type_="foreignkey")
    op.drop_column("group_role_assignments", "role_id")
    op.add_column("policies", sa.Column("scope", sa.String(length=20), nullable=False))
    op.create_index(op.f("ix_policies_scope"), "policies", ["scope"], unique=False)
    op.add_column("roles", sa.Column("scope", sa.String(length=20), nullable=False))
    op.add_column(
        "roles",
        sa.Column(
            "policy_names",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_roles_scope"), "roles", ["scope"], unique=False)
    op.add_column("user_role_assignments", sa.Column("role_name", sa.String(length=255), nullable=False))
    op.drop_index(op.f("ix_user_role_assignments_role_id"), table_name="user_role_assignments")
    op.drop_index(
        op.f("ix_ura_user_role_global"), table_name="user_role_assignments", postgresql_where="(project_id IS NULL)"
    )
    op.create_index(
        "ix_ura_user_role_global",
        "user_role_assignments",
        ["user_id", "role_name"],
        unique=True,
        postgresql_where=sa.text("project_id IS NULL"),
    )
    op.drop_index(
        op.f("ix_ura_user_role_project"),
        table_name="user_role_assignments",
        postgresql_where="(project_id IS NOT NULL)",
    )
    op.create_index(
        "ix_ura_user_role_project",
        "user_role_assignments",
        ["user_id", "role_name", "project_id"],
        unique=True,
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.create_index(op.f("ix_user_role_assignments_role_name"), "user_role_assignments", ["role_name"], unique=False)
    op.drop_constraint(op.f("user_role_assignments_role_id_fkey"), "user_role_assignments", type_="foreignkey")
    op.drop_column("user_role_assignments", "role_id")
    # ### end Alembic commands ###

    # CUSTOM: Deduplicate credential_type rows before adding unique constraint (AAP-72262).
    # Keeps the row with the earliest created_at per name, reassigns credentials to it.
    op.execute("""
        WITH survivors AS (
            SELECT DISTINCT ON (name) id, name
            FROM credential_types
            ORDER BY name, created_at ASC, id ASC
        )
        UPDATE credentials
        SET credential_type_id = survivors.id
        FROM credential_types AS ct
        JOIN survivors ON survivors.name = ct.name
        WHERE credentials.credential_type_id = ct.id
          AND ct.id != survivors.id
    """)
    op.execute("""
        DELETE FROM credential_types
        WHERE id NOT IN (
            SELECT DISTINCT ON (name) id
            FROM credential_types
            ORDER BY name, created_at ASC, id ASC
        )
    """)
    # END CUSTOM

    op.drop_index("ix_credential_types_name", table_name="credential_types")
    op.create_index(
        op.f("ix_credential_types_name"),
        "credential_types",
        ["name"],
        unique=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Revert credential_type unique index
    op.drop_index(op.f("ix_credential_types_name"), table_name="credential_types")
    op.create_index(
        op.f("ix_credential_types_name"),
        "credential_types",
        ["name"],
        unique=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_role_assignments", sa.Column("role_id", sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(
        op.f("user_role_assignments_role_id_fkey"), "user_role_assignments", "roles", ["role_id"], ["id"]
    )
    op.drop_index(op.f("ix_user_role_assignments_role_name"), table_name="user_role_assignments")
    op.drop_index(
        "ix_ura_user_role_project",
        table_name="user_role_assignments",
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_ura_user_role_project"),
        "user_role_assignments",
        ["user_id", "role_id", "project_id"],
        unique=True,
        postgresql_where="(project_id IS NOT NULL)",
    )
    op.drop_index(
        "ix_ura_user_role_global", table_name="user_role_assignments", postgresql_where=sa.text("project_id IS NULL")
    )
    op.create_index(
        op.f("ix_ura_user_role_global"),
        "user_role_assignments",
        ["user_id", "role_id"],
        unique=True,
        postgresql_where="(project_id IS NULL)",
    )
    op.create_index(op.f("ix_user_role_assignments_role_id"), "user_role_assignments", ["role_id"], unique=False)
    op.drop_column("user_role_assignments", "role_name")
    op.drop_index(op.f("ix_roles_scope"), table_name="roles")
    op.drop_column("roles", "policy_names")
    op.drop_column("roles", "scope")
    op.drop_index(op.f("ix_policies_scope"), table_name="policies")
    op.drop_column("policies", "scope")
    op.add_column("group_role_assignments", sa.Column("role_id", sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(
        op.f("group_role_assignments_role_id_fkey"), "group_role_assignments", "roles", ["role_id"], ["id"]
    )
    op.drop_index(op.f("ix_group_role_assignments_role_name"), table_name="group_role_assignments")
    op.drop_index(
        "ix_gra_group_role_project",
        table_name="group_role_assignments",
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_gra_group_role_project"),
        "group_role_assignments",
        ["group_id", "role_id", "project_id"],
        unique=True,
        postgresql_where="(project_id IS NOT NULL)",
    )
    op.drop_index(
        "ix_gra_group_role_global", table_name="group_role_assignments", postgresql_where=sa.text("project_id IS NULL")
    )
    op.create_index(
        op.f("ix_gra_group_role_global"),
        "group_role_assignments",
        ["group_id", "role_id"],
        unique=True,
        postgresql_where="(project_id IS NULL)",
    )
    op.create_index(op.f("ix_group_role_assignments_role_id"), "group_role_assignments", ["role_id"], unique=False)
    op.drop_column("group_role_assignments", "role_name")
    op.create_table(
        "role_policies",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "labels",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("role_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("policy_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["policy_id"], ["policies.id"], name=op.f("role_policies_policy_id_fkey")),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name=op.f("role_policies_role_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("role_policies_pkey")),
        sa.UniqueConstraint(
            "role_id",
            "policy_id",
            name=op.f("uq_role_policies_role_policy"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_role_policies_updated_at"), "role_policies", ["updated_at"], unique=False)
    op.create_index(op.f("ix_role_policies_role_id"), "role_policies", ["role_id"], unique=False)
    op.create_index(op.f("ix_role_policies_policy_id"), "role_policies", ["policy_id"], unique=False)
    op.create_index(op.f("ix_role_policies_id"), "role_policies", ["id"], unique=False)
    op.create_index(op.f("ix_role_policies_created_at"), "role_policies", ["created_at"], unique=False)
    # ### end Alembic commands ###
