"""add_webhook_trigger_service_accounts

Revision ID: 460f6329a0a1
Revises: 59f3fc6d24fc
Create Date: 2026-07-20 13:14:20.945113

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "460f6329a0a1"
down_revision: str | Sequence[str] | None = "59f3fc6d24fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_trigger_service_accounts",
        sa.Column("webhook_trigger_id", sa.Uuid(), nullable=False),
        sa.Column("service_account_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["service_account_id"], ["service_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["webhook_trigger_id"], ["webhook_triggers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("webhook_trigger_id", "service_account_id"),
    )
    op.create_index(
        "ix_wt_sa_service_account_id",
        "webhook_trigger_service_accounts",
        ["service_account_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_wt_sa_service_account_id", table_name="webhook_trigger_service_accounts")
    op.drop_table("webhook_trigger_service_accounts")
    # ### end Alembic commands ###
