"""credential hard delete

Revision ID: 471c6755b5b1
Revises: 219dcd505ee5
Create Date: 2026-04-23 09:55:46.709181

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "471c6755b5b1"
down_revision: str | Sequence[str] | None = "219dcd505ee5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # CUSTOM: Purge soft-deleted credentials before dropping columns.
    # Their secret material was already hard-deleted; only the empty shell remains.
    op.execute("DELETE FROM credentials WHERE deleted_at IS NOT NULL")
    # END CUSTOM

    # CUSTOM: Replace partial unique index with unconditional unique index.
    # The partial index filtered on deleted_at which is being removed.
    op.drop_index("ix_credentials_name_unique", table_name="credentials")
    op.create_index("ix_credentials_name_unique", "credentials", ["name"], unique=True)
    # END CUSTOM

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_credentials_deleted_at"), table_name="credentials")
    op.drop_index(op.f("ix_credentials_deleted_by"), table_name="credentials")
    op.drop_constraint(op.f("credentials_deleted_by_fkey"), "credentials", type_="foreignkey")
    op.drop_column("credentials", "deleted_by")
    op.drop_column("credentials", "deleted_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credentials", sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.add_column("credentials", sa.Column("deleted_by", sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f("credentials_deleted_by_fkey"), "credentials", "users", ["deleted_by"], ["id"])
    op.create_index(op.f("ix_credentials_deleted_by"), "credentials", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_credentials_deleted_at"), "credentials", ["deleted_at"], unique=False)
    # ### end Alembic commands ###

    # CUSTOM: Restore partial unique index for soft-delete filtering.
    op.drop_index("ix_credentials_name_unique", table_name="credentials")
    op.create_index(
        "ix_credentials_name_unique",
        "credentials",
        ["name"],
        unique=True,
        postgresql_where="deleted_at IS NULL",
    )
    # END CUSTOM
