"""add server_default to users is_enabled and is_builtin

Revision ID: 526156818004
Revises: dc24c1c70a1a
Create Date: 2026-04-27 16:23:17.197871

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "526156818004"
down_revision: str | Sequence[str] | None = "dc24c1c70a1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "is_enabled", existing_type=sa.BOOLEAN(), server_default=sa.text("true"), existing_nullable=False
    )
    op.alter_column(
        "users", "is_builtin", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_builtin", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
    op.alter_column("users", "is_enabled", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
    # ### end Alembic commands ###
