"""create runtime_settings table

Creates the ``runtime_settings`` table with PostgreSQL enum types
``settingcategory`` and ``settingvaluetype``. Keys are dot-namespaced
(e.g. ``context_manager.max_total_tokens``) and globally unique.

This migration also serves as a merge point for the settings branch
and the post-LLM token usage branch.

Revision ID: 5fe2f0efbc02
Revises: a1b2c3d4e5f6, ff2dde768eeb
Create Date: 2026-04-03 16:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5fe2f0efbc02"
down_revision: str | Sequence[str] | None = ("a1b2c3d4e5f6", "ff2dde768eeb")
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# CUSTOM: PostgreSQL enum types must be created explicitly before the table.
# Alembic autogenerate does not handle CREATE TYPE with checkfirst; we do it
# here so the migration is idempotent on re-runs and safe under concurrent startup.
settingcategory = postgresql.ENUM(
    "ai_llm",
    "workflow_execution",
    "integrations",
    "system",
    "context_manager",
    "application",
    name="settingcategory",
)
settingvaluetype = postgresql.ENUM(
    "string",
    "integer",
    "float",
    "boolean",
    "json",
    name="settingvaluetype",
)
# END CUSTOM


def upgrade() -> None:
    """Upgrade schema."""
    # CUSTOM: create enum types first (checkfirst=True makes this idempotent)
    settingcategory.create(op.get_bind(), checkfirst=True)
    settingvaluetype.create(op.get_bind(), checkfirst=True)
    # END CUSTOM

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runtime_settings",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column(
            "labels", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("default_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "value_type",
            postgresql.ENUM(
                "string", "integer", "float", "boolean", "json", name="settingvaluetype", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            postgresql.ENUM(
                "ai_llm",
                "workflow_execution",
                "integrations",
                "system",
                "context_manager",
                "application",
                name="settingcategory",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("group", sa.String(length=255), nullable=True),
        sa.Column("requires_restart", sa.Boolean(), nullable=False),
        sa.Column("cache_ttl_seconds", sa.Integer(), nullable=True),
        sa.Column("validation_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runtime_settings")),
        sa.UniqueConstraint("key", name="uq_runtime_settings_key"),
    )
    op.create_index(op.f("ix_runtime_settings_category"), "runtime_settings", ["category"], unique=False)
    op.create_index(op.f("ix_runtime_settings_created_at"), "runtime_settings", ["created_at"], unique=False)
    op.create_index(op.f("ix_runtime_settings_id"), "runtime_settings", ["id"], unique=False)
    op.create_index(op.f("ix_runtime_settings_key"), "runtime_settings", ["key"], unique=False)
    op.create_index(op.f("ix_runtime_settings_name"), "runtime_settings", ["name"], unique=False)
    op.create_index(op.f("ix_runtime_settings_updated_at"), "runtime_settings", ["updated_at"], unique=False)
    op.create_index(op.f("ix_runtime_settings_value_type"), "runtime_settings", ["value_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_runtime_settings_value_type"), table_name="runtime_settings")
    op.drop_index(op.f("ix_runtime_settings_updated_at"), table_name="runtime_settings")
    op.drop_index(op.f("ix_runtime_settings_name"), table_name="runtime_settings")
    op.drop_index(op.f("ix_runtime_settings_key"), table_name="runtime_settings")
    op.drop_index(op.f("ix_runtime_settings_id"), table_name="runtime_settings")
    op.drop_index(op.f("ix_runtime_settings_created_at"), table_name="runtime_settings")
    op.drop_index(op.f("ix_runtime_settings_category"), table_name="runtime_settings")
    op.drop_table("runtime_settings")
    # ### end Alembic commands ###

    # CUSTOM: drop enum types after the table is gone
    settingvaluetype.drop(op.get_bind(), checkfirst=True)
    settingcategory.drop(op.get_bind(), checkfirst=True)
    # END CUSTOM
