"""require_project_id_on_scoped_resources

Revision ID: 6c19b1305293
Revises: 91a1c39e802e
Create Date: 2026-06-24 12:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c19b1305293"
down_revision: str | Sequence[str] | None = "91a1c39e802e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Make project_id non-nullable on project-scoped resources.

    Backfills NULL values before adding NOT NULL constraints:
    - workflows: assigns to built-in project
    - executions: copies from parent workflow
    - approval_requests: copies from parent execution
    """
    # CUSTOM: backfill NULL project_id values before adding NOT NULL (AAP-79237)
    conn = op.get_bind()

    # Backfill workflows: assign NULL project_id rows to the built-in project
    conn.execute(
        sa.text("""
            UPDATE workflows
            SET project_id = (
                SELECT id FROM projects
                WHERE is_builtin = true AND deleted_at IS NULL
                LIMIT 1
            )
            WHERE project_id IS NULL
            AND EXISTS (
                SELECT 1 FROM projects
                WHERE is_builtin = true AND deleted_at IS NULL
            )
        """)
    )

    # Backfill executions: copy project_id from parent workflow
    conn.execute(
        sa.text("""
            UPDATE executions e
            SET project_id = w.project_id
            FROM workflows w
            WHERE e.workflow_id = w.id
            AND e.project_id IS NULL
            AND w.project_id IS NOT NULL
        """)
    )

    # Backfill approval_requests: copy project_id from parent execution
    conn.execute(
        sa.text("""
            UPDATE approval_requests ar
            SET project_id = e.project_id
            FROM executions e
            WHERE ar.execution_id = e.id
            AND ar.project_id IS NULL
            AND e.project_id IS NOT NULL
        """)
    )
    # END CUSTOM

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("workflows", "project_id", existing_type=sa.Uuid(), nullable=False)
    op.alter_column("executions", "project_id", existing_type=sa.Uuid(), nullable=False)
    op.alter_column("approval_requests", "project_id", existing_type=sa.Uuid(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert project_id columns to nullable."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("approval_requests", "project_id", existing_type=sa.Uuid(), nullable=True)
    op.alter_column("executions", "project_id", existing_type=sa.Uuid(), nullable=True)
    op.alter_column("workflows", "project_id", existing_type=sa.Uuid(), nullable=True)
    # ### end Alembic commands ###
