"""add depends_on to runtime_settings

Revision ID: 9d7d700e0504
Revises: 6b39839bdd4d
Create Date: 2026-05-06 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d7d700e0504"
down_revision: str | Sequence[str] | None = "b889ea197887"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "runtime_settings",
        sa.Column("depends_on", sa.String(255), nullable=True),
    )
    # ### end Alembic commands ###

    # CUSTOM: enforce dot-namespaced key format on depends_on
    op.create_check_constraint(
        "depends_on_format_check",
        "runtime_settings",
        "depends_on IS NULL OR depends_on ~ '^[a-z_][a-z0-9_]*(\\.[a-z_][a-z0-9_]*)+$'",
    )
    # END CUSTOM


def downgrade() -> None:
    """Downgrade schema."""
    # CUSTOM: remove format check before dropping column
    op.drop_constraint("depends_on_format_check", "runtime_settings", type_="check")
    # END CUSTOM

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runtime_settings", "depends_on")
    # ### end Alembic commands ###
