"""set null on tool_id fk for tool_executions and usage_counters

Make tool_executions.tool_id nullable and add ON DELETE SET NULL to both
tool_executions.tool_id and usage_counters.tool_id so that hard-deleting
a tool preserves execution history and usage counters.

Revision ID: b727b6ef0ef4
Revises: 0154989e046f
Create Date: 2026-07-20 14:31:31.957300

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b727b6ef0ef4"
down_revision: str | Sequence[str] | None = "0154989e046f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add ON DELETE SET NULL to tool_id FKs."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: tool_executions.tool_id was already made nullable in 0154989e046f.
    op.drop_constraint(op.f("tool_executions_tool_id_fkey"), "tool_executions", type_="foreignkey")
    op.create_foreign_key(
        "tool_executions_tool_id_fkey", "tool_executions", "tools", ["tool_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint(op.f("usage_counters_tool_id_fkey"), "usage_counters", type_="foreignkey")
    op.create_foreign_key(
        "usage_counters_tool_id_fkey", "usage_counters", "tools", ["tool_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Restore original tool_id FKs without ON DELETE SET NULL."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("usage_counters_tool_id_fkey", "usage_counters", type_="foreignkey")
    op.create_foreign_key(op.f("usage_counters_tool_id_fkey"), "usage_counters", "tools", ["tool_id"], ["id"])
    op.drop_constraint("tool_executions_tool_id_fkey", "tool_executions", type_="foreignkey")
    op.create_foreign_key(op.f("tool_executions_tool_id_fkey"), "tool_executions", "tools", ["tool_id"], ["id"])
    # NOTE: nullable=False revert is handled by downgrade of 0154989e046f.
    # ### end Alembic commands ###
