"""add project_id to file_metadata

Add project_id column to the file_metadata table for project-scoped
resource isolation (AAP-78143). Authorization is purely project-based;
user ownership (created_by) is not stored on the resource.

Revision ID: b810b197d930
Revises: a0f042999fd8
Create Date: 2026-06-11

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b810b197d930"
down_revision: str | Sequence[str] | None = "a0f042999fd8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add project_id column to file_metadata."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file_metadata", sa.Column("project_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_file_metadata_project_id"), "file_metadata", ["project_id"], unique=False)
    op.create_foreign_key("fk_file_metadata_project_id", "file_metadata", "projects", ["project_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove project_id column from file_metadata."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_file_metadata_project_id", "file_metadata", type_="foreignkey")
    op.drop_index(op.f("ix_file_metadata_project_id"), table_name="file_metadata")
    op.drop_column("file_metadata", "project_id")
    # ### end Alembic commands ###
