"""add_project_id_to_invocations_and_require_on_file_metadata

Revision ID: c311711bb5c8
Revises: 66a534c1807b
Create Date: 2026-06-25 12:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c311711bb5c8"
down_revision: str | Sequence[str] | None = "66a534c1807b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add project_id to invocations and make it non-nullable on file_metadata.

    - invocations: adds new project_id column, backfills from default project, sets NOT NULL
    - file_metadata: backfills NULL project_id, sets NOT NULL
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invocations", sa.Column("project_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_invocations_project_id"), "invocations", ["project_id"], unique=False)
    op.create_foreign_key("fk_invocations_project_id_projects", "invocations", "projects", ["project_id"], ["id"])
    # ### end Alembic commands ###

    # CUSTOM: backfill NULL project_id values before adding NOT NULL (AAP-79237 Part 2)
    conn = op.get_bind()

    # Backfill invocations: assign to the default project
    conn.execute(
        sa.text("""
            UPDATE invocations
            SET project_id = (
                SELECT id FROM projects
                WHERE is_default = true AND deleted_at IS NULL
                LIMIT 1
            )
            WHERE project_id IS NULL
            AND EXISTS (
                SELECT 1 FROM projects
                WHERE is_default = true AND deleted_at IS NULL
            )
        """)
    )

    # Backfill file_metadata: assign to the default project
    conn.execute(
        sa.text("""
            UPDATE file_metadata
            SET project_id = (
                SELECT id FROM projects
                WHERE is_default = true AND deleted_at IS NULL
                LIMIT 1
            )
            WHERE project_id IS NULL
            AND EXISTS (
                SELECT 1 FROM projects
                WHERE is_default = true AND deleted_at IS NULL
            )
        """)
    )
    # END CUSTOM

    op.alter_column("invocations", "project_id", existing_type=sa.Uuid(), nullable=False)
    op.alter_column("file_metadata", "project_id", existing_type=sa.Uuid(), nullable=False)


def downgrade() -> None:
    """Revert: drop project_id from invocations, make file_metadata.project_id nullable."""
    op.alter_column("file_metadata", "project_id", existing_type=sa.Uuid(), nullable=True)
    op.alter_column("invocations", "project_id", existing_type=sa.Uuid(), nullable=True)
    op.drop_constraint("fk_invocations_project_id_projects", "invocations", type_="foreignkey")
    op.drop_index(op.f("ix_invocations_project_id"), table_name="invocations")
    op.drop_column("invocations", "project_id")
