"""add_is_builtin_to_workflows_and_projects

Revision ID: f3be35b8c6a9
Revises: af3fdc174f37
Create Date: 2026-06-13 12:57:46.890962

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3be35b8c6a9"
down_revision: str | Sequence[str] | None = "af3fdc174f37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("is_builtin", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.create_index(op.f("ix_projects_is_builtin"), "projects", ["is_builtin"], unique=False)
    op.add_column("workflows", sa.Column("is_builtin", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.create_index(op.f("ix_workflows_is_builtin"), "workflows", ["is_builtin"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflows_is_builtin"), table_name="workflows")
    op.drop_column("workflows", "is_builtin")
    op.drop_index(op.f("ix_projects_is_builtin"), table_name="projects")
    op.drop_column("projects", "is_builtin")
    # ### end Alembic commands ###
