"""add global_revocation_timestamp table

Revision ID: ffc5b31c7ef4
Revises: 6b39839bdd4d
Create Date: 2026-05-06 12:38:33.302650

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffc5b31c7ef4"
down_revision: str | Sequence[str] | None = "6b39839bdd4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_revocation_timestamp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("revoked_before", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_singleton", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint("is_singleton = true", name="ck_global_revocation_singleton"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("is_singleton"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("global_revocation_timestamp")
    # ### end Alembic commands ###
