/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/approvals': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List approval requests
     * @description Retrieve a paginated list of approval requests with optional filtering.
     *
     *     Use this endpoint to:
     *     - View pending approvals requiring action
     *     - Review historical approval decisions
     *     - Filter by execution, status, or date range
     */
    get: operations['listApprovals']
    put?: never
    /**
     * Create approval request
     * @description Create a new approval request for a workflow execution.
     *
     *     This is an internal endpoint called by the Workflows component when
     *     a workflow execution reaches an approval node. It should not be called
     *     directly by end users.
     */
    post: operations['createApproval']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/approvals/{approval_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get approval request
     * @description Retrieve details of a specific approval request.
     *
     *     The response includes:
     *     - Full request context (workflow inputs, completed step outputs)
     *     - Next steps for both approval and rejection paths
     *     - Decision history if already decided
     */
    get: operations['getApproval']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Submit approval decision
     * @description Submit an approval decision (approve or reject).
     *
     *     Only pending approval requests can be decided. Attempting to modify an approval
     *     that is already approved, rejected, expired, or cancelled will return an error.
     *
     *     When a decision is submitted:
     *     1. The approval request status is updated
     *     2. The decided_by, decided_at, and decision_notes fields are populated
     *     3. A signal is sent to the workflow to resume execution on the appropriate path
     */
    patch: operations['decideApproval']
    trace?: never
  }
  '/approvals/batch': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Batch approve/reject multiple requests
     * @description Submit decisions for multiple approval requests at once.
     *
     *     This endpoint processes each decision independently. If some decisions fail,
     *     the successful ones are still recorded. The response includes detailed results
     *     for each decision.
     *
     *     Use cases:
     *     - Approving multiple related requests at once
     *     - Bulk rejection of stale or irrelevant requests
     */
    post: operations['batchDecideApprovals']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ApprovalRequest: components['schemas']['BaseResource'] & {
      /**
       * Format: uuid
       * @description Parent workflow execution ID
       */
      execution_id: string
      /** @description Activity ID from workflow definition */
      approval_node_id: string
      /** @description Display name for the approval request */
      name: string
      status: components['schemas']['ApprovalStatus']
      /**
       * Format: date-time
       * @description When this request expires (null = no timeout)
       */
      timeout_at?: string | null
      /** @description First activity that executes if approved */
      next_step_approved: components['schemas']['ActivitySummary']
      /** @description First activity that executes if rejected (null if path ends workflow) */
      next_step_rejected?: components['schemas']['ActivitySummary'] | null
      workflow_context: components['schemas']['WorkflowContext']
      /** @description User who made the decision (captures name at decision time) */
      decided_by?: components['schemas']['UserReference'] | null
      /**
       * Format: date-time
       * @description When decision was made
       */
      decided_at?: string | null
      /** @description Notes provided with the decision */
      decision_notes?: string | null
    }
    /**
     * Approval Status
     * @description Current state of a human approval request
     * @enum {string}
     */
    ApprovalStatus: 'pending' | 'approved' | 'rejected' | 'expired' | 'cancelled'
    /**
     * Activity Summary
     * @description Summary of a workflow activity for display in approval context.
     *     Provides enough information for UI rendering without exposing
     *     full activity configuration details.
     */
    ActivitySummary: {
      /**
       * @description Activity ID from workflow definition
       * @example apply_changes
       */
      id: string
      /**
       * @description Human-readable activity name
       * @example Apply Changes
       */
      name: string
      /**
       * @description Activity type (task, approval, parallel, etc.)
       * @example task
       */
      type: string
    }
    /**
     * Approval Create Request
     * @description Request payload for creating an approval request.
     *     This is an internal schema used by the Workflows component.
     */
    ApprovalCreateRequest: {
      /**
       * Format: uuid
       * @description Parent workflow execution ID
       */
      execution_id: string
      /** @description Activity ID from workflow definition */
      approval_node_id: string
      /** @description Display name for the approval request */
      name: string
      /**
       * Format: date-time
       * @description When this request expires (null = no timeout)
       */
      timeout_at?: string | null
      /** @description First activity that executes if approved */
      next_step_approved: components['schemas']['ActivitySummary']
      /** @description First activity that executes if rejected (null if path ends workflow) */
      next_step_rejected?: components['schemas']['ActivitySummary'] | null
      workflow_context: components['schemas']['WorkflowContext']
    }
    /**
     * Workflow Context
     * @description Essential context for approvers to make a decision.
     *     Contains workflow identification, inputs, and the output from the immediately preceding activity.
     *     For current workflow state (especially in parallel workflows), approvers should
     *     navigate to the workflow execution canvas via the execution link.
     * @example {
     *       "workflow_version_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
     *       "workflow_name": "Production Deployment",
     *       "inputs": {
     *         "target_environment": "production",
     *         "version": "2.1.0",
     *         "requested_by": "alice@example.com"
     *       },
     *       "previous_step": {
     *         "id": "security_scan",
     *         "name": "Security Scan",
     *         "type": "task",
     *         "output": {
     *           "vulnerabilities_found": 0,
     *           "scan_duration_seconds": 120
     *         }
     *       }
     *     }
     */
    WorkflowContext: {
      /**
       * Format: uuid
       * @description ID of the workflow version being executed
       */
      workflow_version_id: string
      /** @description Name of the workflow */
      workflow_name: string
      /** @description Original workflow input parameters (structure varies per workflow) */
      inputs: {
        [key: string]: unknown
      }
      previous_step?: components['schemas']['PreviousStepContext']
    }
    /**
     * Previous Step Context
     * @description The activity that immediately preceded this approval node, including its output.
     *     Null if the approval node is the first activity in the workflow.
     */
    PreviousStepContext: {
      /**
       * @description Activity ID from workflow definition
       * @example security_scan
       */
      id: string
      /**
       * @description Human-readable activity name
       * @example Security Scan
       */
      name: string
      /**
       * @description Activity type (task, approval, parallel, etc.)
       * @example task
       */
      type: string
      /** @description Output from the activity (structure varies per activity type) */
      output?: {
        [key: string]: unknown
      } | null
    }
    /**
     * Approval Decision Status
     * @description Status values that can be submitted in approval decisions.
     *     This is a subset of ApprovalRequestStatus containing only user-actionable values.
     * @enum {string}
     */
    ApprovalDecisionStatus: 'approved' | 'rejected'
    /**
     * Approval Decision Request
     * @description Request payload for submitting an approval decision.
     *
     *     Status values:
     *     - approved: Approver grants the request, workflow continues on approval path
     *     - rejected: Approver denies the request, workflow continues on rejection path
     *     - cancelled: Internal use only - set by workflow engine when parent workflow is cancelled.
     *       Will be restricted to service accounts when authentication is implemented.
     */
    ApprovalDecisionRequest: {
      status: components['schemas']['ApprovalDecisionStatus']
      /** @description Optional notes explaining the decision */
      notes?: string | null
    }
    /**
     * Batch Approval Decision Status
     * @description Status values that can be submitted in batch approval decisions.
     *     This is a subset of ApprovalRequestStatus containing only system-actionable values.
     * @enum {string}
     */
    BatchApprovalDecisionStatus: 'approved' | 'rejected' | 'expired' | 'cancelled'
    /**
     * Batch Approval Decision
     * @description Single decision within a batch approval request
     */
    BatchApprovalDecision: {
      /**
       * Format: uuid
       * @description ID of the approval request
       */
      approval_id: string
      status: components['schemas']['BatchApprovalDecisionStatus']
      /** @description Optional notes explaining the decision */
      notes?: string | null
    }
    /**
     * Batch Approval Request
     * @description Request payload for submitting multiple approval decisions at once
     */
    BatchApprovalRequest: {
      /** @description List of approval decisions to submit */
      decisions: components['schemas']['BatchApprovalDecision'][]
    }
    /**
     * Batch Approval Result
     * @description Confirmation for a single approval within a batch response.
     */
    BatchApprovalResult: {
      /**
       * Format: uuid
       * @description ID of the approval request
       */
      approval_id: string
      /** @description Whether the decision was successfully recorded */
      success: boolean
      /** @description New status after the decision (if successful) */
      status?: components['schemas']['ApprovalStatus']
      /**
       * Format: date-time
       * @description When decision was recorded (if successful)
       */
      decided_at?: string | null
      /** @description User who made the decision (if successful) */
      decided_by?: components['schemas']['UserReference'] | null
      /** @description Notes provided with the decision (echoed back from request) */
      decision_notes?: string | null
      /** @description Error message if the decision failed */
      error?: string | null
    }
    /**
     * Batch Approval Response
     * @description Response for batch approval submission
     */
    BatchApprovalResponse: {
      /** @description Individual results for each decision */
      results: components['schemas']['BatchApprovalResult'][]
      /** @description Number of successfully processed decisions */
      total_success: number
      /** @description Number of failed decisions */
      total_failed: number
    }
    /**
     * User Reference
     * @description Minimal user identification for embedding in other resources
     */
    UserReference: {
      /**
       * Format: uuid
       * @description User's unique identifier
       */
      id: string
      /** @description User's display name at time of action */
      name: string
    }
    Error: components['schemas']['ErrorData']
    /**
     * Paginated Response Base
     * @description Pagination metadata structure for list responses
     */
    ResourcesResponseBase: {
      /**
       * Next Page Cursor
       * @description Cursor for next page of results
       * @example eyJpZCI6InV1aWQifQ
       */
      next?: string | null
      /**
       * Previous Page Cursor
       * @description Cursor for previous page of results
       * @example eyJpZCI6InV1aWQifQ
       */
      prev?: string | null
      /**
       * Total Count
       * @description Total count of resources (only when include_total=true)
       * @example 150
       */
      total?: number | null
    }
    /**
     * Base Resource
     * @description Foundational schema for all API resources with system-managed metadata
     */
    BaseResource: {
      /**
       * Resource ID
       * Format: uuid
       * @description Unique identifier for the resource
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      readonly id: string
      /**
       * Created At
       * Format: date-time
       * @description Timestamp when resource was created
       * @example 2025-10-09T12:00:00Z
       */
      readonly created_at: string
      /**
       * Updated At
       * Format: date-time
       * @description Timestamp when resource was last updated
       * @example 2025-10-09T12:30:00Z
       */
      readonly updated_at: string
      /**
       * Labels
       * @description Key-value pairs for resource labeling and filtering
       * @default {}
       * @example {
       *       "environment": "production",
       *       "region": "us-east-1",
       *       "team": "platform"
       *     }
       */
      labels?: {
        [key: string]: string
      }
    }
    /**
     * RFC 9457 Problem Details
     * @description RFC 9457 Problem Details format for error responses.
     *     This format provides machine-readable and human-readable error information
     *     with consistent structure for all API error responses.
     */
    ErrorData: {
      /**
       * Problem Type URI
       * @description URI reference identifying the problem type
       * @example https://api.nexus.com/errors/validation-error
       */
      type: string
      /**
       * Problem Title
       * @description Short, human-readable summary of the problem
       * @example Validation Error
       */
      title: string
      /**
       * Problem Detail
       * @description Human-readable explanation specific to this occurrence
       * @example Field 'name' must be between 1 and 255 characters
       */
      detail: string
      /**
       * Error Code
       * @description Machine-readable error code for programmatic handling
       * @example VALIDATION_ERROR
       */
      code: string
      /**
       * Retryable Flag
       * @description Whether this error can be retried
       * @example false
       */
      retryable: boolean
      /**
       * Problem Instance
       * @description URI reference identifying the specific occurrence
       * @example /api/v1/workflows
       */
      instance?: string | null
    }
  }
  responses: never
  parameters: {
    /**
     * @description Number of resources to return per page
     * @example 20
     */
    limitParam: number
    /**
     * @description Opaque cursor for pagination (from previous response)
     * @example eyJpZCI6InV1aWQifQ
     */
    cursorParam: string
    /**
     * @description Sort order for resources.
     *     - Ascending: `field` (e.g., `name`)
     *     - Descending: `-field` (e.g., `-created_at`)
     * @example -created_at
     */
    sortParam: string
    createdAtFilterParam: string & {
      /**
       * Equals
       * Format: date-time
       * @description Exact match of creation timestamp. ?created_at[eq]=<timestamp>
       */
      eq?: string
      /**
       * Greater Than
       * Format: date-time
       * @description Greater than comparison. ?created_at[gt]=<timestamp>
       */
      gt?: string
      /**
       * Greater Than Or Equal
       * Format: date-time
       * @description Greater than or equal comparison. ?created_at[gte]=<timestamp>
       */
      gte?: string
      /**
       * Less Than
       * Format: date-time
       * @description Less than comparison. ?created_at[lt]=<timestamp>
       */
      lt?: string
      /**
       * Less Than Or Equal
       * Format: date-time
       * @description Less than or equal comparison. ?created_at[lte]=<timestamp>
       */
      lte?: string
    }
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  listApprovals: {
    parameters: {
      query?: {
        /**
         * @description Number of resources to return per page
         * @example 20
         */
        limit?: components['parameters']['limitParam']
        /**
         * @description Opaque cursor for pagination (from previous response)
         * @example eyJpZCI6InV1aWQifQ
         */
        cursor?: components['parameters']['cursorParam']
        /**
         * @description Sort order for resources.
         *     - Ascending: `field` (e.g., `name`)
         *     - Descending: `-field` (e.g., `-created_at`)
         * @example -created_at
         */
        sort?: components['parameters']['sortParam']
        /** @description Filter by approval status */
        status?: components['schemas']['ApprovalStatus']
        /** @description Filter by parent workflow execution ID */
        execution_id?: string
        created_at?: components['parameters']['createdAtFilterParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Paginated list of approval requests */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResourcesResponseBase'] & {
            resources: components['schemas']['ApprovalRequest'][]
          }
        }
      }
      /** @description Invalid query parameters */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  createApproval: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ApprovalCreateRequest']
      }
    }
    responses: {
      /** @description Approval request created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApprovalRequest']
        }
      }
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
      /** @description Approval request already exists for this execution and approval node */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  getApproval: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Approval request ID */
        approval_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Approval request details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApprovalRequest']
        }
      }
      /** @description Approval request not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  decideApproval: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Approval request ID */
        approval_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ApprovalDecisionRequest']
      }
    }
    responses: {
      /** @description Approval decision recorded and workflow resumed */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApprovalRequest']
        }
      }
      /** @description Invalid request payload (e.g., invalid status value) */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
      /** @description Approval request not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
      /** @description Approval already decided or workflow cancelled */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  batchDecideApprovals: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BatchApprovalRequest']
      }
    }
    responses: {
      /** @description Batch processing complete (may include partial failures) */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BatchApprovalResponse']
        }
      }
      /** @description Invalid request format */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
}
