/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/files': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Upload Files
     * @description Upload files independently of invocations for later use in agent execution.
     *
     *     Returns file_ids that can be stored in workflow configuration and passed to invocations
     *     via context_data.file_ids. Files are validated, stored, and queued for document conversion.
     *
     *     **Supported Formats:** PDF, DOC, DOCX, TXT, MD
     *     **Max File Size:** 10 MB per file (configurable via file_upload_max_size_mb)
     *     **Max File Count:** 10 files per request (configurable via file_upload_max_files)
     *
     *     **Security Note:** Internal file paths are never exposed in API responses.
     */
    post: operations['uploadFiles']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * File Upload Response
     * @description Response from POST /files endpoint
     */
    FileUploadResponse: {
      /**
       * File IDs
       * @description List of file IDs for later reference in invocations
       * @example [
       *       "550e8400-e29b-41d4-a716-446655440000"
       *     ]
       */
      file_ids: string[]
      /**
       * Files
       * @description Metadata for each uploaded file
       */
      files: components['schemas']['FileUploadInfo'][]
    }
    /**
     * File Upload Info
     * @description Metadata for an uploaded file (excludes internal file_path for security)
     */
    FileUploadInfo: {
      /**
       * File ID
       * Format: uuid
       * @description Unique file identifier (UUID)
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      file_id: string
      /**
       * Filename
       * @description Original filename from upload
       * @example document.pdf
       */
      filename: string
      /**
       * Size Bytes
       * @description File size in bytes
       * @example 524288
       */
      size_bytes: number
      /**
       * MIME Type
       * @description Detected MIME type of the file
       * @example application/pdf
       */
      mime_type: string
      status: components['schemas']['FileProcessingStatus']
    }
    /**
     * File Processing Status
     * @description Current status of file processing/conversion
     * @example pending_conversion
     * @enum {string}
     */
    FileProcessingStatus: 'pending_conversion' | 'converting' | 'converted' | 'conversion_failed'
    /**
     * File Metadata
     * @description Internal file metadata including storage path (used in context_data)
     */
    FileMetadata: {
      /**
       * Format: uuid
       * @description Unique file identifier (UUID)
       */
      id: string
      /** @description Original filename */
      filename: string
      /** @description File size in bytes */
      size_bytes: number
      /** @description MIME type (e.g., application/pdf) */
      mime_type: string
      /** @description Path to file in storage directory */
      file_path: string
      status: components['schemas']['FileProcessingStatus']
    }
    /**
     * Error Response
     * @description Standardized error response structure
     */
    Error: {
      /**
       * Error Code
       * @description Error category/code in snake_case format
       * @example validation_error
       */
      error: string
      /**
       * Error Message
       * @description Human-readable error message
       * @example The 'name' field is required
       */
      message: string
      /**
       * Error Details
       * @description Additional error details or context
       * @example Field 'name' must be between 1 and 255 characters
       */
      details?: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  uploadFiles: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': {
          /** @description Files to upload (1-10 files, max 10MB each) */
          files: string[]
        }
      }
    }
    responses: {
      /** @description Files uploaded successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FileUploadResponse']
        }
      }
      /** @description Bad Request - Validation error */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Internal Server Error - Storage failure */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
}
