/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/policies': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List policies
     * @description List policies with filtering and pagination.
     */
    get: operations['list_policies']
    put?: never
    /**
     * Create a custom policy
     * @description Create a new custom policy with one or more statements.
     *     Requires: policy:create permission (admin role).
     */
    post: operations['create_policy']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/policies/{policy_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a policy by ID */
    get: operations['get_policy']
    /**
     * Update a policy (full replacement)
     * @description Update a policy. Builtin policies cannot be modified.
     *     Requires: policy:update permission (admin role).
     */
    put: operations['update_policy_put']
    post?: never
    /**
     * Delete a policy
     * @description Delete a policy. Builtin policies cannot be deleted.
     *     Requires: policy:delete permission (admin role).
     */
    delete: operations['delete_policy']
    options?: never
    head?: never
    /**
     * Update a policy
     * @description Update a policy. Builtin policies cannot be modified.
     *     Requires: policy:update permission (admin role).
     */
    patch: operations['update_policy']
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * Policy Statement
     * @description A single policy statement defining an access rule
     */
    PolicyStatementSchema: {
      /**
       * @description Whether this statement allows or denies access
       * @enum {string}
       */
      effect: 'allow' | 'deny'
      /** @description List of resource_type:action strings (e.g., "workflow:read") */
      actions: string[]
      /**
       * @description Scope of the statement (any = all resources, self = owned resources)
       * @enum {string}
       */
      scope: 'any' | 'self'
      /** @description Optional attribute-based conditions */
      conditions?: {
        [key: string]: unknown
      } | null
    }
    /**
     * Policy Create
     * @description Request body for creating a policy
     */
    PolicyCreate: {
      /** @description Unique policy name */
      name: string
      /** @description Policy description */
      description?: string | null
      /** @description Policy statements */
      statements: components['schemas']['PolicyStatementSchema'][]
      /**
       * @description Key-value labels
       * @default {}
       */
      labels?: {
        [key: string]: string
      }
      /**
       * Format: uuid
       * @description Project scope (null for system-level)
       */
      project_id?: string | null
    }
    /**
     * Policy Update
     * @description Request body for updating a policy (partial)
     */
    PolicyUpdate: {
      /** @description Update policy name */
      name?: string | null
      /** @description Update description */
      description?: string | null
      /** @description Update statements */
      statements?: components['schemas']['PolicyStatementSchema'][] | null
      /** @description Update labels */
      labels?: {
        [key: string]: string
      } | null
    }
    /**
     * Policy Read
     * @description Response body for a policy
     */
    PolicyRead: {
      /**
       * Format: uuid
       * @description Policy UUID
       */
      id: string
      /** @description Policy name */
      name: string
      /** @description Policy description */
      description?: string | null
      /**
       * @description Policy statements
       * @default []
       */
      statements?: {
        [key: string]: unknown
      }[]
      /**
       * @description Whether this is a builtin policy
       * @default false
       */
      is_builtin?: boolean
      /**
       * Format: uuid
       * @description Project scope (null for system-level)
       */
      project_id?: string | null
      /**
       * @description Key-value labels
       * @default {}
       */
      labels?: {
        [key: string]: unknown
      }
      /** @description True when the policy is not scoped to a specific project (computed from project_id) */
      readonly is_system_scoped?: boolean
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      created_at?: string | null
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updated_at?: string | null
    }
    PolicyListResponse: components['schemas']['ResourcesResponseBase'] & {
      resources: components['schemas']['PolicyRead'][]
    }
    /**
     * Paginated Response Base
     * @description Pagination metadata structure for list responses
     */
    ResourcesResponseBase: {
      /**
       * Next Page Cursor
       * @description Cursor for next page of results
       * @example eyJpZCI6InV1aWQifQ
       */
      next?: string | null
      /**
       * Previous Page Cursor
       * @description Cursor for previous page of results
       * @example eyJpZCI6InV1aWQifQ
       */
      prev?: string | null
      /**
       * Total Count
       * @description Total count of resources (only when include_total=true)
       * @example 150
       */
      total?: number | null
    }
    /**
     * RFC 9457 Problem Details
     * @description RFC 9457 Problem Details format for error responses.
     *     This format provides machine-readable and human-readable error information
     *     with consistent structure for all API error responses.
     */
    ErrorData: {
      /**
       * Problem Type URI
       * @description URI reference identifying the problem type
       * @example https://api.nexus.com/errors/validation-error
       */
      type: string
      /**
       * Problem Title
       * @description Short, human-readable summary of the problem
       * @example Validation Error
       */
      title: string
      /**
       * Problem Detail
       * @description Human-readable explanation specific to this occurrence
       * @example Field 'name' must be between 1 and 255 characters
       */
      detail: string
      /**
       * Error Code
       * @description Machine-readable error code for programmatic handling
       * @example VALIDATION_ERROR
       */
      code: string
      /**
       * Retryable Flag
       * @description Whether this error can be retried
       * @example false
       */
      retryable: boolean
      /**
       * Problem Instance
       * @description URI reference identifying the specific occurrence
       * @example /api/v1/workflows
       */
      instance?: string | null
    }
  }
  responses: never
  parameters: {
    /**
     * @description Number of resources to return per page
     * @example 20
     */
    limitParam: number
    /**
     * @description Opaque cursor for pagination (from previous response)
     * @example eyJpZCI6InV1aWQifQ
     */
    cursorParam: string
    /**
     * @description Whether to include total count in response (may impact performance)
     * @example true
     */
    includeTotalParam: boolean
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_policies: {
    parameters: {
      query?: {
        /**
         * @description Number of resources to return per page
         * @example 20
         */
        limit?: components['parameters']['limitParam']
        /**
         * @description Opaque cursor for pagination (from previous response)
         * @example eyJpZCI6InV1aWQifQ
         */
        cursor?: components['parameters']['cursorParam']
        /**
         * @description Whether to include total count in response (may impact performance)
         * @example true
         */
        include_total?: components['parameters']['includeTotalParam']
        /** @description Sort field and direction (e.g., 'name', '-created_at') */
        sort?: string
        /** @description Filter by policy name */
        name?: string
        /** @description Filter by builtin status */
        is_builtin?: boolean
        /** @description Filter by project scope */
        project_id?: string
        /** @description When true, return only policies whose actions are valid for project-scoped roles */
        project_eligible?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Paginated list of policies */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PolicyListResponse']
        }
      }
    }
  }
  create_policy: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PolicyCreate']
      }
    }
    responses: {
      /** @description Policy created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PolicyRead']
        }
      }
      /** @description Policy name conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  get_policy: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Policy UUID */
        policy_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Policy details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PolicyRead']
        }
      }
      /** @description Policy not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  update_policy_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Policy UUID */
        policy_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PolicyUpdate']
      }
    }
    responses: {
      /** @description Updated policy */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PolicyRead']
        }
      }
      /** @description Policy not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  delete_policy: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Policy UUID */
        policy_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Policy deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Policy not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  update_policy: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Policy UUID */
        policy_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PolicyUpdate']
      }
    }
    responses: {
      /** @description Updated policy */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PolicyRead']
        }
      }
      /** @description Policy not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
}
