/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/user-role-assignments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List all user-role assignments
     * @description List all system-level user-to-role assignments.
     */
    get: operations['list_user_role_assignments']
    put?: never
    /**
     * Assign a role to a user
     * @description Assign a role directly to a user at the system level.
     *     Requires: admin permission.
     */
    post: operations['assign_user_role']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user-role-assignments/{assignment_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Remove a user-role assignment
     * @description Remove a user-to-role assignment.
     *     Requires: admin permission.
     */
    delete: operations['revoke_user_role_assignment']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * User Role Assignment Create
     * @description Request body for assigning a role to a user
     */
    UserRoleAssignmentCreate: {
      /**
       * Format: uuid
       * @description User UUID
       */
      user_id: string
      /**
       * Format: uuid
       * @description Role UUID
       */
      role_id: string
    }
    /**
     * User Role Assignment Read
     * @description Response body for a user-to-role assignment
     */
    UserRoleAssignmentRead: {
      /** @description Assignment ID */
      id: string
      /** @description User UUID */
      user_id: string
      /** @description Username */
      username: string
      /** @description Role UUID */
      role_id: string
      /** @description Role name */
      role_name: string
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      created_at?: string | null
    }
    /**
     * RFC 9457 Problem Details
     * @description RFC 9457 Problem Details format for error responses.
     *     This format provides machine-readable and human-readable error information
     *     with consistent structure for all API error responses.
     */
    ErrorData: {
      /**
       * Problem Type URI
       * @description URI reference identifying the problem type
       * @example https://api.nexus.com/errors/validation-error
       */
      type: string
      /**
       * Problem Title
       * @description Short, human-readable summary of the problem
       * @example Validation Error
       */
      title: string
      /**
       * Problem Detail
       * @description Human-readable explanation specific to this occurrence
       * @example Field 'name' must be between 1 and 255 characters
       */
      detail: string
      /**
       * Error Code
       * @description Machine-readable error code for programmatic handling
       * @example VALIDATION_ERROR
       */
      code: string
      /**
       * Retryable Flag
       * @description Whether this error can be retried
       * @example false
       */
      retryable: boolean
      /**
       * Problem Instance
       * @description URI reference identifying the specific occurrence
       * @example /api/v1/workflows
       */
      instance?: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_user_role_assignments: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of user-role assignments */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRoleAssignmentRead'][]
        }
      }
    }
  }
  assign_user_role: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserRoleAssignmentCreate']
      }
    }
    responses: {
      /** @description Role assigned to user */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRoleAssignmentRead']
        }
      }
      /** @description User or role not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
      /** @description Assignment already exists */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  revoke_user_role_assignment: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Assignment UUID */
        assignment_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Assignment removed */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Assignment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
}
