/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Users
     * @description List users with visibility filtering and pagination.
     *
     *     Users with ``user:read:any`` see all users.
     *     Users with ``user:read:self`` see only themselves.
     */
    get: operations['list_users']
    put?: never
    /**
     * Create User
     * @description Create a new local user.
     */
    post: operations['create_user']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{user_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get User
     * @description Get a user by ID.
     */
    get: operations['get_user']
    put?: never
    post?: never
    /**
     * Delete User
     * @description Soft delete a user.
     */
    delete: operations['delete_user']
    options?: never
    head?: never
    /**
     * Update User
     * @description Update a user.
     *
     *     Supports partial updates - only provided fields are updated.
     */
    patch: operations['update_user']
    trace?: never
  }
  '/users/{user_id}/groups': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List User Groups
     * @description List groups that a user belongs to.
     */
    get: operations['list_user_groups']
    /**
     * Set User Groups
     * @description Set a user's group memberships declaratively.
     *
     *     Replace all current memberships with the provided list of group IDs.
     *     An empty list removes the user from all groups.
     */
    put: operations['set_user_groups']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{user_id}/identities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List User Identities
     * @description List federated identities for a user.
     */
    get: operations['list_user_identities']
    put?: never
    /**
     * Attach User Identity
     * @description Attach a federated identity from another user to this user.
     */
    post: operations['attach_user_identity']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{user_id}/identities/{identity_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Detach User Identity
     * @description Detach (hard-delete) a federated identity from a user.
     */
    delete: operations['detach_user_identity']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/groups': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Groups
     * @description Retrieve list of groups with visibility filtering.
     *
     *     Users with ``group:read:any`` see all groups.
     *     Users with ``group:read:self`` see only their own groups.
     */
    get: operations['list_groups']
    put?: never
    /**
     * Create Group
     * @description Create a new group for organizing users.
     */
    post: operations['create_group']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/groups/{group_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Group
     * @description Retrieve a group by its UUID.
     */
    get: operations['get_group']
    put?: never
    post?: never
    /**
     * Delete Group
     * @description Soft delete a group.
     */
    delete: operations['delete_group']
    options?: never
    head?: never
    /**
     * Update Group
     * @description Update a group partially; only provided fields are changed.
     */
    patch: operations['update_group']
    trace?: never
  }
  '/groups/{group_id}/members': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Members
     * @description List members of a group with pagination.
     */
    get: operations['list_members']
    put?: never
    /**
     * Add Member
     * @description Add a user to a group.
     */
    post: operations['add_member']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/groups/{group_id}/members/{user_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Remove Member
     * @description Remove a user from a group.
     */
    delete: operations['remove_member']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{user_id}/role_assignments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List User Role Assignments
     * @description List role assignments for a specific user.
     */
    get: operations['list_user_role_assignments']
    put?: never
    /**
     * Create User Role Assignment
     * @description Assign a role to this user.
     */
    post: operations['create_user_role_assignment']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{user_id}/role_assignments/{assignment_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete User Role Assignment
     * @description Remove a role assignment from this user.
     */
    delete: operations['delete_user_role_assignment']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/groups/{group_id}/role_assignments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Group Role Assignments
     * @description List role assignments for a specific group.
     */
    get: operations['list_group_role_assignments']
    put?: never
    /**
     * Create Group Role Assignment
     * @description Assign a role to this group.
     */
    post: operations['create_group_role_assignment']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/groups/{group_id}/role_assignments/{assignment_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Delete Group Role Assignment
     * @description Remove a role assignment from this group.
     */
    delete: operations['delete_group_role_assignment']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * UserCreate
     * @description Schema for creating a new local user (POST /users).
     *
     *     Excludes auto-generated fields: id, created_at, updated_at, last_login, preferences.
     */
    UserCreate: {
      /**
       * Username
       * @description Unique username
       */
      username: string
      /**
       * Email
       * @description Email address
       */
      email?: string | null
      /**
       * Full Name
       * @description User's display name
       */
      full_name: string
      /**
       * Password
       * Format: password
       * @description Plaintext password (will be hashed)
       */
      password: string
      /**
       * Is Enabled
       * @description Whether the user account is enabled
       * @default true
       */
      is_enabled?: boolean
      /**
       * Group Names
       * @description Groups to assign the user to. Omit to use the default (users group). Pass an empty list to skip group assignment.
       */
      group_names?: string[] | null
    }
    /**
     * UserUpdate
     * @description Schema for updating a user (PATCH /users/{id}).
     *
     *     All fields are optional for partial updates.
     */
    UserUpdate: {
      /**
       * Username
       * @description Update username
       */
      username?: string | null
      /**
       * Full Name
       * @description Update display name
       */
      full_name?: string | null
      /**
       * Email
       * @description Update email address
       */
      email?: string | null
      /**
       * Password
       * @description New password (will be hashed). Omit to keep current password.
       */
      password?: string | null
      /**
       * Is Enabled
       * @description Enable or disable user account
       */
      is_enabled?: boolean | null
    }
    /**
     * AuthType
     * @description Authentication type for users.
     * @enum {string}
     */
    AuthType: 'local' | 'federated'
    /**
     * UserRead
     * @description Schema for user response (GET /users/{id}).
     *
     *     Includes all user fields except sensitive data (password_hash, preferences).
     */
    UserRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Username */
      username: string
      /** Email */
      email?: string | null
      /** Full Name */
      full_name: string
      /** Is Enabled */
      is_enabled: boolean
      /**
       * Is Builtin
       * @default false
       */
      is_builtin?: boolean
      /** @default local */
      auth_type?: components['schemas']['AuthType']
      /**
       * Auth Sources
       * @description Identity provider names for this user
       * @default []
       */
      auth_sources?: string[]
      /** Last Login */
      last_login?: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * ResourcesResponse[UserRead]
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    ResourcesResponse_UserRead_: {
      /**
       * Next
       * @description Cursor for next page of results
       */
      next?: string | null
      /**
       * Prev
       * @description Cursor for previous page of results
       */
      prev?: string | null
      /**
       * Total
       * @description Total count of resources (only when include_total=true)
       */
      total?: number | null
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['UserRead'][]
    }
    /**
     * UserGroupsSet
     * @description Schema for declaratively setting a user's group memberships (PUT /users/{id}/groups).
     *
     *     The provided list replaces all current memberships. An empty list removes
     *     the user from all groups.
     */
    UserGroupsSet: {
      /**
       * Group Ids
       * @description Complete list of group IDs the user should belong to
       */
      group_ids?: string[]
    }
    /**
     * UserIdentityRead
     * @description Schema for user identity response.
     */
    UserIdentityRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * User Id
       * Format: uuid
       */
      user_id: string
      /**
       * Identity Provider Id
       * Format: uuid
       */
      identity_provider_id: string
      /** Issuer */
      issuer: string
      /** Subject */
      subject: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
      /** Last Used At */
      last_used_at?: string | null
      /**
       * Provider Name
       * @default
       */
      provider_name?: string
    }
    /**
     * UserIdentityListResponse
     * @description Paginated list of user identities.
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    UserIdentityListResponse: {
      /**
       * Next
       * @description Cursor for next page of results
       */
      next?: string | null
      /**
       * Prev
       * @description Cursor for previous page of results
       */
      prev?: string | null
      /**
       * Total
       * @description Total count of resources (only when include_total=true)
       */
      total?: number | null
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['UserIdentityRead'][]
    }
    /**
     * UserIdentityAttach
     * @description Schema for attaching an identity to a user.
     */
    UserIdentityAttach: {
      /**
       * Identity Id
       * Format: uuid
       */
      identity_id: string
    }
    /**
     * GroupCreate
     * @description Schema for creating a new group (POST /groups).
     */
    GroupCreate: {
      /**
       * Name
       * @description Group name
       */
      name: string
      /**
       * Description
       * @description Group description
       */
      description?: string | null
    }
    /**
     * GroupUpdate
     * @description Schema for updating a group (PATCH /groups/{id}).
     *
     *     All fields are optional for partial updates.
     */
    GroupUpdate: {
      /**
       * Name
       * @description Update group name
       */
      name?: string | null
      /**
       * Description
       * @description Update group description
       */
      description?: string | null
    }
    /**
     * GroupRead
     * @description Schema for group response (GET /groups/{id}).
     *
     *     Includes all fields from the database table model.
     */
    GroupRead: components['schemas']['BaseResource'] & {
      /** Name */
      name: string
      /** Description */
      description?: string | null
      /**
       * Is Builtin
       * @default false
       */
      is_builtin?: boolean
      /** Created By */
      created_by?: string | null
      /**
       * Source
       * @default local
       */
      source?: string
      /**
       * Member Count
       * @default 0
       */
      member_count?: number
    }
    /**
     * MembershipSource
     * @description Describes how a user got membership in a group.
     */
    MembershipSource: {
      /**
       * Type
       * @description Source type: 'manual' or 'idp'
       */
      type: string
      /**
       * Provider Name
       * @description IdP name if source is 'idp'
       */
      provider_name?: string | null
      /**
       * Provider Id
       * @description IdP ID if source is 'idp'
       */
      provider_id?: string | null
    }
    /**
     * UserGroupRead
     * @description Group response with membership source info for a specific user.
     */
    UserGroupRead: components['schemas']['BaseResource'] & {
      /** Name */
      name: string
      /** Description */
      description?: string | null
      /**
       * Is Builtin
       * @default false
       */
      is_builtin?: boolean
      /** Created By */
      created_by?: string | null
      /**
       * Source
       * @default local
       */
      source?: string
      /**
       * Member Count
       * @default 0
       */
      member_count?: number
      /**
       * Membership Sources
       * @description How this user was assigned to this group
       */
      membership_sources?: components['schemas']['MembershipSource'][]
    }
    /**
     * GroupMemberRead
     * @description User response with membership source info for a specific group.
     */
    GroupMemberRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Username */
      username: string
      /** Email */
      email?: string | null
      /** Full Name */
      full_name: string
      /** Is Enabled */
      is_enabled: boolean
      /**
       * Is Builtin
       * @default false
       */
      is_builtin?: boolean
      /** @default local */
      auth_type?: components['schemas']['AuthType']
      /**
       * Auth Sources
       * @description Identity provider names for this user
       * @default []
       */
      auth_sources?: string[]
      /** Last Login */
      last_login?: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
      /**
       * Membership Sources
       * @description How this user was assigned to this group
       */
      membership_sources?: components['schemas']['MembershipSource'][]
    }
    /**
     * ResourcesResponse[GroupRead]
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    ResourcesResponse_GroupRead_: {
      /**
       * Next
       * @description Cursor for next page of results
       */
      next?: string | null
      /**
       * Prev
       * @description Cursor for previous page of results
       */
      prev?: string | null
      /**
       * Total
       * @description Total count of resources (only when include_total=true)
       */
      total?: number | null
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['GroupRead'][]
    }
    /**
     * ResourcesResponse[UserGroupRead]
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    ResourcesResponse_UserGroupRead_: {
      /**
       * Next
       * @description Cursor for next page of results
       */
      next?: string | null
      /**
       * Prev
       * @description Cursor for previous page of results
       */
      prev?: string | null
      /**
       * Total
       * @description Total count of resources (only when include_total=true)
       */
      total?: number | null
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['UserGroupRead'][]
    }
    /**
     * ResourcesResponse[GroupMemberRead]
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    ResourcesResponse_GroupMemberRead_: {
      /**
       * Next
       * @description Cursor for next page of results
       */
      next?: string | null
      /**
       * Prev
       * @description Cursor for previous page of results
       */
      prev?: string | null
      /**
       * Total
       * @description Total count of resources (only when include_total=true)
       */
      total?: number | null
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['GroupMemberRead'][]
    }
    /**
     * GroupMemberAdd
     * @description Schema for adding a member to a group (POST /groups/{id}/members).
     */
    GroupMemberAdd: {
      /**
       * User Id
       * Format: uuid
       * @description UUID of the user to add to the group
       */
      user_id: string
    }
    /**
     * GroupMemberAddResponse
     * @description Response schema for adding a member to a group.
     */
    GroupMemberAddResponse: {
      /**
       * Message
       * @description Confirmation message
       * @default Member added successfully
       */
      message?: string
    }
    /**
     * SubResourceRoleAssignmentCreate
     * @description Request body for creating a role assignment from a sub-resource endpoint.
     *
     *     principal_type and principal_id come from the URL path.
     */
    SubResourceRoleAssignmentCreate: {
      /** Role Name */
      role_name: string
      /** Project Id */
      project_id?: string | null
    }
    /**
     * RoleAssignmentRead
     * @description Response body for a role assignment.
     */
    RoleAssignmentRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Principal Type */
      principal_type: string
      /**
       * Principal Id
       * Format: uuid
       */
      principal_id: string
      /** Principal Name */
      principal_name: string
      /** Role Name */
      role_name: string
      /** Role Description */
      role_description?: string | null
      /**
       * Role Policies
       * @default []
       */
      role_policies?: string[]
      /** Project Id */
      project_id?: string | null
      /** Project Name */
      project_name?: string | null
      /**
       * Is Builtin
       * @default false
       */
      is_builtin?: boolean
      /** Created At */
      created_at?: string | null
    }
    /**
     * RoleAssignmentListResponse
     * @description Paginated response for role assignments.
     */
    RoleAssignmentListResponse: WithRequired<components['schemas']['ResourcesResponseBase'], 'resources'> & {
      resources: components['schemas']['RoleAssignmentRead'][]
    }
    /**
     * ErrorData
     * @description RFC 9457 Problem Details format for error event data.
     *     This model is used for streaming error events and follows the RFC 9457 Problem Details specification. It provides machine-readable and human-readable error information with consistent structure.
     *     Attributes:
     *         type: URI reference identifying the problem type
     *         title: Short, human-readable summary of the problem
     *         detail: Human-readable explanation specific to this occurrence
     *         code: Machine-readable error code for programmatic handling
     *         retryable: Whether this error can be retried by creating a new invocation
     *         instance: Optional URI reference identifying the specific occurrence
     * @example {
     *       "type": "https://api.nexus.com/errors/llm-error",
     *       "title": "LLM Rate Limit Exceeded",
     *       "detail": "OpenRouter API rate limit exceeded. Please try again in a few moments.",
     *       "code": "RATE_LIMIT_EXCEEDED",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     * @example {
     *       "type": "https://api.nexus.com/errors/timeout-error",
     *       "title": "Streaming Timeout",
     *       "detail": "LLM streaming timed out after 30 seconds",
     *       "code": "STREAM_TIMEOUT",
     *       "retryable": true,
     *       "instance": "/invocations/550e8400-e29b-41d4-a716-446655440000"
     *     }
     */
    ErrorData: {
      /**
       * Type
       * @description URI reference identifying the problem type
       * @example https://api.nexus.com/errors/llm-error
       */
      type: string
      /**
       * Title
       * @description Short, human-readable summary of the problem
       * @example LLM Service Unavailable
       */
      title: string
      /**
       * Detail
       * @description Human-readable explanation specific to this occurrence
       * @example OpenRouter API returned error: rate limit exceeded. Please try again in a few moments.
       */
      detail: string
      /**
       * Code
       * @description Machine-readable error code for programmatic handling
       * @example RATE_LIMIT_EXCEEDED
       */
      code: string
      /**
       * Retryable
       * @description Whether this error can be retried by creating a new invocation
       * @example true
       */
      retryable: boolean
      /**
       * Instance
       * @description Optional URI reference identifying the specific occurrence
       * @example /invocations/550e8400-e29b-41d4-a716-446655440000
       */
      instance?: string | null
    }
    /**
     * Base Resource
     * @description Foundational schema for all API resources with system-managed metadata
     */
    BaseResource: {
      /**
       * Resource ID
       * Format: uuid
       * @description Unique identifier for the resource
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      readonly id?: string
      /**
       * Created At
       * Format: date-time
       * @description Timestamp when resource was created
       * @example 2025-10-09T12:00:00Z
       */
      readonly created_at?: string
      /**
       * Updated At
       * Format: date-time
       * @description Timestamp when resource was last updated
       * @example 2025-10-09T12:30:00Z
       */
      readonly updated_at?: string
      /**
       * Labels
       * @description Key-value pairs for resource labeling and filtering
       * @default {}
       * @example {
       *       "environment": "production",
       *       "region": "us-east-1",
       *       "team": "platform"
       *     }
       */
      labels?: {
        [key: string]: string
      }
    }
    /**
     * Paginated Response Base
     * @description Pagination metadata structure for list responses
     * @example {
     *       "next": "eyJpZCI6InV1aWQifQ",
     *       "total": 150
     *     }
     * @example {
     *       "next": "eyJpZCI6Im5leHQifQ",
     *       "prev": "eyJpZCI6InByZXYifQ"
     *     }
     */
    ResourcesResponseBase: {
      /**
       * Next
       * @description Cursor for next page of results
       */
      next?: string | null
      /**
       * Prev
       * @description Cursor for previous page of results
       */
      prev?: string | null
      /**
       * Total
       * @description Total count of resources (only when include_total=true)
       */
      total?: number | null
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources?: unknown[]
    }
  }
  responses: {
    /** @description Bad Request */
    BadRequestError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.nexus.com/errors/bad-request",
         *       "title": "Bad Request",
         *       "detail": "The request was malformed or contained invalid parameters",
         *       "code": "BAD_REQUEST",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Unauthorized */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.nexus.com/errors/unauthorized",
         *       "title": "Unauthorized",
         *       "detail": "Authentication is required to access this resource",
         *       "code": "UNAUTHORIZED",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Forbidden */
    ForbiddenError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.nexus.com/errors/forbidden",
         *       "title": "Forbidden",
         *       "detail": "You do not have permission to access this resource",
         *       "code": "FORBIDDEN",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Not Found */
    NotFoundError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.nexus.com/errors/not-found",
         *       "title": "Resource Not Found",
         *       "detail": "No resource exists with the provided identifier",
         *       "code": "NOT_FOUND",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Conflict */
    ConflictError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.nexus.com/errors/conflict",
         *       "title": "Conflict",
         *       "detail": "The request conflicts with the current state of the resource",
         *       "code": "CONFLICT",
         *       "retryable": false
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Validation Error */
    ValidationError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.nexus.com/errors/validation-error",
         *       "title": "Validation Error",
         *       "detail": "Field 'name' must be between 1 and 255 characters",
         *       "code": "VALIDATION_ERROR",
         *       "retryable": false,
         *       "instance": "/api/v1/workflows"
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
    /** @description Internal Server Error */
    InternalServerError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        /**
         * @example {
         *       "type": "https://api.nexus.com/errors/internal-error",
         *       "title": "Internal Server Error",
         *       "detail": "An unexpected error occurred",
         *       "code": "INTERNAL_ERROR",
         *       "retryable": true
         *     }
         */
        'application/problem+json': components['schemas']['ErrorData']
      }
    }
  }
  parameters: {
    /** @description Maximum number of results per page */
    limitParam: number
    /** @description Pagination cursor from previous response */
    cursorParam: string | null
    /** @description Sort parameter (e.g., 'name', '-created_at') */
    sortParam: string | null
    /** @description Include total count in response (expensive) */
    includeTotalParam: boolean
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_users: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: components['parameters']['sortParam']
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
        username?: string | null
        full_name?: string | null
        auth_source?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of users */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResourcesResponse_UserRead_']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  create_user: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCreate']
      }
    }
    responses: {
      /** @description User created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  get_user: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  delete_user: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  update_user: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdate']
      }
    }
    responses: {
      /** @description Updated user */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  list_user_groups: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: components['parameters']['sortParam']
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
      }
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of groups the user belongs to */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResourcesResponse_UserGroupRead_']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  set_user_groups: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserGroupsSet']
      }
    }
    responses: {
      /** @description Updated group memberships */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResourcesResponse_UserGroupRead_']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  list_user_identities: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserIdentityListResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  attach_user_identity: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserIdentityAttach']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserIdentityRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  detach_user_identity: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
        identity_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  list_groups: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: components['parameters']['sortParam']
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of groups */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResourcesResponse_GroupRead_']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  create_group: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GroupCreate']
      }
    }
    responses: {
      /** @description Group created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  get_group: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Group UUID */
        group_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Group details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  delete_group: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Group UUID */
        group_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Group deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  update_group: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Group UUID */
        group_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GroupUpdate']
      }
    }
    responses: {
      /** @description Updated group */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  list_members: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: components['parameters']['sortParam']
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
      }
      header?: never
      path: {
        /** @description Group UUID */
        group_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of group members */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ResourcesResponse_GroupMemberRead_']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  add_member: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Group UUID */
        group_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GroupMemberAdd']
      }
    }
    responses: {
      /** @description Member added */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupMemberAddResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  remove_member: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Group UUID */
        group_id: string
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Member removed */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  list_user_role_assignments: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: components['parameters']['sortParam']
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
        role_name?: string | null
        project_id?: string | null
      }
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of role assignments for this user */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RoleAssignmentListResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  create_user_role_assignment: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SubResourceRoleAssignmentCreate']
      }
    }
    responses: {
      /** @description Role assignment created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RoleAssignmentRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  delete_user_role_assignment: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
        assignment_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Assignment removed */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  list_group_role_assignments: {
    parameters: {
      query?: {
        /** @description Maximum number of results per page */
        limit?: components['parameters']['limitParam']
        /** @description Pagination cursor from previous response */
        cursor?: components['parameters']['cursorParam']
        /** @description Sort parameter (e.g., 'name', '-created_at') */
        sort?: components['parameters']['sortParam']
        /** @description Include total count in response (expensive) */
        include_total?: components['parameters']['includeTotalParam']
        role_name?: string | null
        project_id?: string | null
      }
      header?: never
      path: {
        group_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of role assignments for this group */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RoleAssignmentListResponse']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  create_group_role_assignment: {
    parameters: {
      query?: never
      header?: never
      path: {
        group_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SubResourceRoleAssignmentCreate']
      }
    }
    responses: {
      /** @description Role assignment created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RoleAssignmentRead']
        }
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
  delete_group_role_assignment: {
    parameters: {
      query?: never
      header?: never
      path: {
        group_id: string
        assignment_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Assignment removed */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequestError']
      401: components['responses']['UnauthorizedError']
      403: components['responses']['ForbiddenError']
      404: components['responses']['NotFoundError']
      409: components['responses']['ConflictError']
      422: components['responses']['ValidationError']
      500: components['responses']['InternalServerError']
    }
  }
}
type WithRequired<T, K extends keyof T> = T & {
  [P in K]-?: T[P]
}
