/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List users
     * @description Retrieve list of users with filtering and pagination
     */
    get: operations['list_users']
    put?: never
    /**
     * Create a new local user
     * @description Create a new local user account with username and password
     */
    post: operations['create_user']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{user_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get user by ID
     * @description Retrieve a user by their UUID
     */
    get: operations['get_user']
    put?: never
    post?: never
    /**
     * Delete user
     * @description Soft delete a user account
     */
    delete: operations['delete_user']
    options?: never
    head?: never
    /**
     * Update user
     * @description Partially update a user. Only provided fields are updated.
     *     Include the password field to change the user's password.
     */
    patch: operations['update_user']
    trace?: never
  }
  '/users/{user_id}/groups': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List user's groups
     * @description List groups that a user belongs to
     */
    get: operations['list_user_groups']
    /**
     * Set user's group memberships
     * @description Declaratively set a user's group memberships. The provided list replaces
     *     all current memberships. An empty list removes the user from all groups.
     */
    put: operations['set_user_groups']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/groups': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List groups
     * @description Retrieve list of groups with filtering and pagination
     */
    get: operations['list_groups']
    put?: never
    /**
     * Create a new group
     * @description Create a new group for organizing users
     */
    post: operations['create_group']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/groups/{group_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get group by ID
     * @description Retrieve a group by its UUID
     */
    get: operations['get_group']
    put?: never
    post?: never
    /**
     * Delete group
     * @description Soft delete a group
     */
    delete: operations['delete_group']
    options?: never
    head?: never
    /**
     * Update group
     * @description Partially update a group. Only provided fields are updated.
     */
    patch: operations['update_group']
    trace?: never
  }
  '/groups/{group_id}/members': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List group members
     * @description List members of a group with pagination
     */
    get: operations['list_members']
    put?: never
    /**
     * Add member to group
     * @description Add a local user to a group
     */
    post: operations['add_member']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/groups/{group_id}/members/{user_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Remove member from group
     * @description Remove a user from a group
     */
    delete: operations['remove_member']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    UserCreate: {
      /** @description Unique username */
      username: string
      /**
       * Format: email
       * @description Unique email address
       */
      email: string
      /** @description User's display name */
      full_name: string
      /**
       * Format: password
       * @description Plaintext password (will be hashed)
       */
      password: string
      /**
       * @description User role for access control
       * @default viewer
       * @enum {string}
       */
      role?: 'viewer' | 'creator' | 'approver' | 'administrator'
      /**
       * @description Account activation status
       * @default true
       */
      is_active?: boolean
    }
    UserUpdate: {
      /** @description Update display name */
      full_name?: string
      /**
       * Format: email
       * @description Update email address
       */
      email?: string
      /**
       * Format: password
       * @description New password (will be hashed). Omit to keep current password.
       */
      password?: string
      /**
       * @description Update user role
       * @enum {string}
       */
      role?: 'viewer' | 'creator' | 'approver' | 'administrator'
      /** @description Enable or disable user account */
      is_active?: boolean
    }
    UserRead: {
      /**
       * Format: uuid
       * @description User UUID
       */
      id: string
      /** @description Username */
      username: string
      /**
       * Format: email
       * @description Email address
       */
      email: string
      /** @description Display name */
      full_name: string
      /**
       * @description User role
       * @enum {string}
       */
      role: 'viewer' | 'creator' | 'approver' | 'administrator'
      /** @description Account active status */
      is_active: boolean
      /**
       * Format: date-time
       * @description Last login timestamp
       */
      last_login?: string | null
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      created_at: string
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updated_at: string
    }
    UserListResponse: components['schemas']['ResourcesResponse'] & {
      resources?: components['schemas']['UserRead'][]
    }
    UserGroupsSet: {
      /**
       * @description Complete list of group IDs the user should belong to
       * @default []
       */
      group_ids?: string[]
    }
    GroupCreate: {
      /** @description Unique group name */
      name: string
      /** @description Group description */
      description?: string | null
    }
    GroupUpdate: {
      /** @description Update group name */
      name?: string
      /** @description Update group description */
      description?: string | null
    }
    GroupRead: {
      /**
       * Format: uuid
       * @description Group UUID
       */
      id: string
      /** @description Group name */
      name: string
      /** @description Group description */
      description?: string | null
      /**
       * Format: uuid
       * @description User who created the group
       */
      created_by?: string | null
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      created_at: string
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updated_at: string
    }
    GroupListResponse: components['schemas']['ResourcesResponse'] & {
      resources?: components['schemas']['GroupRead'][]
    }
    GroupMemberAdd: {
      /**
       * Format: uuid
       * @description UUID of the user to add to the group
       */
      user_id: string
    }
    GroupMemberAddResponse: {
      /**
       * @description Confirmation message
       * @default Member added successfully
       */
      message?: string
    }
    /**
     * Paginated Response Base
     * @description Pagination metadata structure for list responses
     */
    ResourcesResponseBase: {
      /**
       * Next Page Cursor
       * @description Cursor for next page of results
       * @example eyJpZCI6InV1aWQifQ
       */
      next?: string | null
      /**
       * Previous Page Cursor
       * @description Cursor for previous page of results
       * @example eyJpZCI6InV1aWQifQ
       */
      prev?: string | null
      /**
       * Total Count
       * @description Total count of resources (only when include_total=true)
       * @example 150
       */
      total?: number | null
    }
    /**
     * Base Resource
     * @description Foundational schema for all API resources with system-managed metadata
     */
    BaseResource: {
      /**
       * Resource ID
       * Format: uuid
       * @description Unique identifier for the resource
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      readonly id: string
      /**
       * Created At
       * Format: date-time
       * @description Timestamp when resource was created
       * @example 2025-10-09T12:00:00Z
       */
      readonly created_at: string
      /**
       * Updated At
       * Format: date-time
       * @description Timestamp when resource was last updated
       * @example 2025-10-09T12:30:00Z
       */
      readonly updated_at: string
      /**
       * Labels
       * @description Key-value pairs for resource labeling and filtering
       * @default {}
       * @example {
       *       "environment": "production",
       *       "region": "us-east-1",
       *       "team": "platform"
       *     }
       */
      labels?: {
        [key: string]: string
      }
    }
    NamedResource: components['schemas']['BaseResource'] & {
      /**
       * Name
       * @description Human-readable name for the resource
       * @example Authentication Service
       */
      name: string
      /**
       * Description
       * @description Detailed description of the resource
       * @example Handles user authentication and authorization workflows
       */
      description?: string | null
    }
    SoftDeletableResource: components['schemas']['BaseResource'] & {
      /**
       * Deleted At
       * Format: date-time
       * @description Timestamp when resource was soft deleted
       * @example 2025-10-09T14:00:00Z
       */
      readonly deleted_at?: string | null
      /**
       * Deleted By
       * Format: uuid
       * @description User who performed the soft delete
       * @example 660e8400-e29b-41d4-a716-446655440000
       */
      readonly deleted_by?: string | null
    }
    UserOwnedResource: components['schemas']['BaseResource'] & {
      /**
       * Created By
       * Format: uuid
       * @description User who created the resource
       * @example 770e8400-e29b-41d4-a716-446655440000
       */
      readonly created_by: string
      /**
       * Updated By
       * Format: uuid
       * @description User who last updated the resource
       * @example 880e8400-e29b-41d4-a716-446655440000
       */
      readonly updated_by?: string | null
    }
    /**
     * Resource
     * @description Composite entity combining all base resource capabilities:
     *     - System metadata (from BaseResource): id, timestamps, labels
     *     - Naming (from NamedResource): name, description
     *     - Soft deletion (from SoftDeletableResource): deletedAt, deletedBy
     *     - Ownership (from UserOwnedResource): created_by, updated_by
     *
     *     This is the recommended base schema for most API resources.
     * @example {
     *       "id": "550e8400-e29b-41d4-a716-446655440000",
     *       "created_at": "2025-10-09T12:00:00Z",
     *       "updated_at": "2025-10-09T12:30:00Z",
     *       "labels": {
     *         "environment": "production",
     *         "region": "us-east-1"
     *       },
     *       "name": "Authentication Service",
     *       "description": "Handles user authentication and authorization",
     *       "deleted_at": null,
     *       "deleted_by": null,
     *       "created_by": "770e8400-e29b-41d4-a716-446655440000",
     *       "updated_by": "880e8400-e29b-41d4-a716-446655440000"
     *     }
     */
    Resource: components['schemas']['NamedResource'] &
      components['schemas']['SoftDeletableResource'] &
      components['schemas']['UserOwnedResource']
    ResourcesResponse: components['schemas']['ResourcesResponseBase'] & {
      /**
       * Resources
       * @description Array of resources in current page
       */
      resources: components['schemas']['Resource'][]
    }
    /**
     * RFC 9457 Problem Details
     * @description RFC 9457 Problem Details format for error responses.
     *     This format provides machine-readable and human-readable error information
     *     with consistent structure for all API error responses.
     */
    ErrorData: {
      /**
       * Problem Type URI
       * @description URI reference identifying the problem type
       * @example https://api.nexus.com/errors/validation-error
       */
      type: string
      /**
       * Problem Title
       * @description Short, human-readable summary of the problem
       * @example Validation Error
       */
      title: string
      /**
       * Problem Detail
       * @description Human-readable explanation specific to this occurrence
       * @example Field 'name' must be between 1 and 255 characters
       */
      detail: string
      /**
       * Error Code
       * @description Machine-readable error code for programmatic handling
       * @example VALIDATION_ERROR
       */
      code: string
      /**
       * Retryable Flag
       * @description Whether this error can be retried
       * @example false
       */
      retryable: boolean
      /**
       * Problem Instance
       * @description URI reference identifying the specific occurrence
       * @example /api/v1/workflows
       */
      instance?: string | null
    }
  }
  responses: never
  parameters: {
    /**
     * @description Number of resources to return per page
     * @example 20
     */
    limitParam: number
    /**
     * @description Opaque cursor for pagination (from previous response)
     * @example eyJpZCI6InV1aWQifQ
     */
    cursorParam: string
    /**
     * @description Whether to include total count in response (may impact performance)
     * @example true
     */
    includeTotalParam: boolean
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_users: {
    parameters: {
      query?: {
        /**
         * @description Number of resources to return per page
         * @example 20
         */
        limit?: components['parameters']['limitParam']
        /**
         * @description Opaque cursor for pagination (from previous response)
         * @example eyJpZCI6InV1aWQifQ
         */
        cursor?: components['parameters']['cursorParam']
        /**
         * @description Whether to include total count in response (may impact performance)
         * @example true
         */
        include_total?: components['parameters']['includeTotalParam']
        /** @description Sort field and direction (e.g., 'username', '-created_at') */
        sort?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of users */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserListResponse']
        }
      }
    }
  }
  create_user: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCreate']
      }
    }
    responses: {
      /** @description User created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRead']
        }
      }
      /** @description Username or email conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  get_user: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User UUID */
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRead']
        }
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  delete_user: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User UUID */
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  update_user: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User UUID */
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdate']
      }
    }
    responses: {
      /** @description Updated user */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRead']
        }
      }
      /** @description Forbidden (e.g., non-admin disabling built-in admin) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
      /** @description Email conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  list_user_groups: {
    parameters: {
      query?: {
        /**
         * @description Number of resources to return per page
         * @example 20
         */
        limit?: components['parameters']['limitParam']
        /**
         * @description Opaque cursor for pagination (from previous response)
         * @example eyJpZCI6InV1aWQifQ
         */
        cursor?: components['parameters']['cursorParam']
      }
      header?: never
      path: {
        /** @description User UUID */
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of groups */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupListResponse']
        }
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  set_user_groups: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User UUID */
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserGroupsSet']
      }
    }
    responses: {
      /** @description Updated group memberships */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupListResponse']
        }
      }
      /** @description User or group not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  list_groups: {
    parameters: {
      query?: {
        /**
         * @description Number of resources to return per page
         * @example 20
         */
        limit?: components['parameters']['limitParam']
        /**
         * @description Opaque cursor for pagination (from previous response)
         * @example eyJpZCI6InV1aWQifQ
         */
        cursor?: components['parameters']['cursorParam']
        /**
         * @description Whether to include total count in response (may impact performance)
         * @example true
         */
        include_total?: components['parameters']['includeTotalParam']
        /** @description Sort field and direction (e.g., 'name', '-created_at') */
        sort?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of groups */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupListResponse']
        }
      }
    }
  }
  create_group: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GroupCreate']
      }
    }
    responses: {
      /** @description Group created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupRead']
        }
      }
      /** @description Group name conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  get_group: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Group UUID */
        group_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Group details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupRead']
        }
      }
      /** @description Group not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  delete_group: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Group UUID */
        group_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Group deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Group not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  update_group: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Group UUID */
        group_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GroupUpdate']
      }
    }
    responses: {
      /** @description Updated group */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupRead']
        }
      }
      /** @description Group not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
      /** @description Group name conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  list_members: {
    parameters: {
      query?: {
        /**
         * @description Number of resources to return per page
         * @example 20
         */
        limit?: components['parameters']['limitParam']
        /**
         * @description Opaque cursor for pagination (from previous response)
         * @example eyJpZCI6InV1aWQifQ
         */
        cursor?: components['parameters']['cursorParam']
      }
      header?: never
      path: {
        /** @description Group UUID */
        group_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of group members */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserListResponse']
        }
      }
      /** @description Group not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  add_member: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Group UUID */
        group_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GroupMemberAdd']
      }
    }
    responses: {
      /** @description Member added */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupMemberAddResponse']
        }
      }
      /** @description User is not a local user */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
      /** @description Group or user not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
      /** @description User already a member */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
  remove_member: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Group UUID */
        group_id: string
        /** @description User UUID */
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Member removed */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description User is not a local user */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
      /** @description Group not found or user not a member */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ErrorData']
        }
      }
    }
  }
}
