/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/activity-types': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List available activity types
     * @description Retrieve all available activity executor types that can be used in workflow definitions.
     *     This endpoint is used for workflow validation, UI tooling, and documentation.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of available activity types with their configuration schemas */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              activity_types?: components['schemas']['ActivityType'][]
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/workflows': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List workflows
     * @description Retrieve a list of workflows with filtering, sorting, and cursor-based pagination.
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter by creator user ID */
          created_by?: string
          /** @description Filter by enabled status */
          is_enabled?: boolean
          /**
           * @description Number of resources to return per page
           * @example 20
           */
          limit?: components['parameters']['limitParam']
          /**
           * @description Opaque cursor for pagination (from previous response)
           * @example eyJpZCI6InV1aWQifQ
           */
          cursor?: components['parameters']['cursorParam']
          /**
           * @description Whether to include total count in response (may impact performance)
           * @example true
           */
          include_total?: components['parameters']['includeTotalParam']
          /**
           * @description Sort order for resources.
           *     - Ascending: `field` (e.g., `name`)
           *     - Descending: `-field` (e.g., `-created_at`)
           * @example -created_at
           */
          sort?: components['parameters']['sortParam']
          /**
           * @description Filter resources by name.
           *     - Exact match: `name=value`
           *     - Contains: `name[contains]=value`
           * @example auth
           */
          name?: components['parameters']['nameFilterParam']
          created_at?: components['parameters']['createdAtFilterParam']
          updated_at?: components['parameters']['updatedAtFilterParam']
          /**
           * @description Filter resources by label key-value pairs.
           *     - Single label: `labels[environment]=production`
           *     - Multiple labels: `labels[environment]=production&labels[region]=us-east-1`
           *     All specified labels must match (AND logic).
           * @example {
           *       "environment": "production",
           *       "region": "us-east-1"
           *     }
           */
          labels?: components['parameters']['labelsFilterParam']
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of workflows */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ResourcesResponseBase'] & {
              resources: components['schemas']['Workflow'][]
            }
          }
        }
      }
    }
    put?: never
    /**
     * Create workflow
     * @description Create a new workflow entity with its initial version. The workflow definition is validated and stored as version 1.
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateWorkflowRequest']
        }
      }
      responses: {
        /** @description Workflow created successfully */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Workflow']
          }
        }
        /** @description Invalid workflow definition */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/workflows/{workflowId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get workflow
     * @description Retrieve a specific workflow by ID including its current active version. Returns workflow metadata along with the version specified by current_version field.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          workflowId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Workflow details including current version information */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['WorkflowWithVersion']
          }
        }
        /** @description Workflow not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    /**
     * Delete workflow (soft delete)
     * @description Soft delete a workflow by setting deleted_at and deleted_by fields. The workflow remains in the database for audit purposes but is excluded from normal queries.
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          workflowId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Workflow soft deleted successfully */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Workflow not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Workflow cannot be deleted (has running executions) */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    options?: never
    head?: never
    /**
     * Update workflow
     * @description Update workflow fields. Supports both metadata updates and workflow definition updates:
     *     - Metadata only (name, description, is_enabled, labels): Updates without creating new version
     *     - With workflow_definition: Validates definition, compares with current version, and creates new version only if definition differs (change detection)
     */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          workflowId: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['PatchWorkflowRequest']
        }
      }
      responses: {
        /** @description Workflow updated successfully (may include new version if workflow_definition changed) */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['WorkflowWithVersion']
          }
        }
        /** @description Invalid workflow definition or validation error */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Workflow not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    trace?: never
  }
  '/workflows/{workflowId}/versions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List workflow versions
     * @description Retrieve all versions for a workflow with cursor-based pagination.
     *     WorkflowVersion entities are read-only and managed automatically by the system.
     *     Versions are ordered by version number descending (newest first) by default.
     */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of resources to return per page
           * @example 20
           */
          limit?: components['parameters']['limitParam']
          /**
           * @description Opaque cursor for pagination (from previous response)
           * @example eyJpZCI6InV1aWQifQ
           */
          cursor?: components['parameters']['cursorParam']
          /**
           * @description Whether to include total count in response (may impact performance)
           * @example true
           */
          include_total?: components['parameters']['includeTotalParam']
          /**
           * @description Sort order for resources.
           *     - Ascending: `field` (e.g., `name`)
           *     - Descending: `-field` (e.g., `-created_at`)
           * @example -created_at
           */
          sort?: components['parameters']['sortParam']
          created_at?: components['parameters']['createdAtFilterParam']
        }
        header?: never
        path: {
          workflowId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of workflow versions */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ResourcesResponseBase'] & {
              resources: components['schemas']['WorkflowVersionResponse'][]
            }
          }
        }
        /** @description Workflow not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/workflows/{workflowId}/versions/{version}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get workflow version
     * @description Retrieve a specific version of a workflow by version number. Returns the complete workflow definition for that version.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          workflowId: string
          /** @description Version number to retrieve */
          version: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Workflow version details */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['WorkflowVersionResponse']
          }
        }
        /** @description Workflow or version not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/executions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List executions
     * @description Retrieve executions with filtering, sorting, and cursor-based pagination.
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter by workflow ID */
          workflow_id?: string
          /** @description Filter by user who created the execution */
          created_by?: string
          /**
           * @description Filter executions by status.
           *     - Exact match: `status=running`
           *     - Multiple values: `status[in]=running,pending`
           */
          status?: components['schemas']['ExecutionStatus'] & {
            /** @description Match any of the comma-separated values. ?status[in]=<val1,val2> */
            in?: string
          }
          /**
           * @description Number of resources to return per page
           * @example 20
           */
          limit?: components['parameters']['limitParam']
          /**
           * @description Opaque cursor for pagination (from previous response)
           * @example eyJpZCI6InV1aWQifQ
           */
          cursor?: components['parameters']['cursorParam']
          /**
           * @description Whether to include total count in response (may impact performance)
           * @example true
           */
          include_total?: components['parameters']['includeTotalParam']
          /**
           * @description Sort order for resources.
           *     - Ascending: `field` (e.g., `name`)
           *     - Descending: `-field` (e.g., `-created_at`)
           * @example -created_at
           */
          sort?: components['parameters']['sortParam']
          created_at?: components['parameters']['createdAtFilterParam']
          updated_at?: components['parameters']['updatedAtFilterParam']
          /**
           * @description Filter resources by label key-value pairs.
           *     - Single label: `labels[environment]=production`
           *     - Multiple labels: `labels[environment]=production&labels[region]=us-east-1`
           *     All specified labels must match (AND logic).
           * @example {
           *       "environment": "production",
           *       "region": "us-east-1"
           *     }
           */
          labels?: components['parameters']['labelsFilterParam']
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of executions */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ResourcesResponseBase'] & {
              resources: components['schemas']['Execution'][]
            }
          }
        }
      }
    }
    put?: never
    /**
     * Create execution
     * @description Start a new workflow execution
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateExecutionRequest']
        }
      }
      responses: {
        /** @description Execution started */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Execution']
          }
        }
        /** @description Workflow not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/executions/{executionId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get execution
     * @description Retrieve details of a specific execution with optional includes.
     *
     *     **Include Parameters**:
     *     - `workflow_definition`: Include the workflow definition from the executed version (for building visualization graph)
     *     - `activities`: Include the list of activities with their current status (for completed executions or fallback)
     *
     *     **Usage**:
     *     - Normal request: `GET /executions/{id}` - returns execution without optional fields
     *     - Visualization: `GET /executions/{id}?include=workflow_definition&include=activities` - for building graph and checking execution status
     */
    get: {
      parameters: {
        query?: {
          /**
           * @description Optional fields to include in the response.
           *     - `workflow_definition`: Include workflow definition for graph building
           *     - `activities`: Include activities list with current status
           * @example [
           *       "workflow_definition",
           *       "activities"
           *     ]
           */
          include?: ('workflow_definition' | 'activities')[]
        }
        header?: never
        path: {
          executionId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Execution details with optional includes */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Execution']
          }
        }
        /** @description Execution not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Control execution
     * @description Pause, resume, or cancel a workflow execution
     */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          executionId: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['ExecutionControlRequest']
        }
      }
      responses: {
        /** @description Execution control applied */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Execution']
          }
        }
        /** @description Execution not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    trace?: never
  }
  '/executions/{executionId}/activities': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List activity executions
     * @description Retrieve activity executions for a workflow execution with cursor-based pagination.
     */
    get: {
      parameters: {
        query?: {
          /**
           * @description Number of resources to return per page
           * @example 20
           */
          limit?: components['parameters']['limitParam']
          /**
           * @description Opaque cursor for pagination (from previous response)
           * @example eyJpZCI6InV1aWQifQ
           */
          cursor?: components['parameters']['cursorParam']
          /**
           * @description Whether to include total count in response (may impact performance)
           * @example true
           */
          include_total?: components['parameters']['includeTotalParam']
          /**
           * @description Sort order for resources.
           *     - Ascending: `field` (e.g., `name`)
           *     - Descending: `-field` (e.g., `-created_at`)
           * @example -created_at
           */
          sort?: components['parameters']['sortParam']
          created_at?: components['parameters']['createdAtFilterParam']
        }
        header?: never
        path: {
          executionId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of activity executions */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ResourcesResponseBase'] & {
              resources: components['schemas']['ActivityExecution'][]
            }
          }
        }
        /** @description Execution not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/executions/{executionId}/signals/approval-decision': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Signal approval decision to workflow
     * @description Send an approval decision signal to a running workflow execution.
     *
     *     This endpoint is called by the approvals component (via WorkflowAPIClient)
     *     to notify a paused workflow that an approval decision has been made.
     *     The workflow will resume on either the approved or rejected path based
     *     on the decision.
     *
     *     The signal is durable - if the workflow is temporarily unavailable,
     *     the signal will be delivered when it becomes available again.
     */
    post: operations['signalApprovalDecision']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/executions/{execution_id}/activities/{activity_id}/signal': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Send signal to activity in workflow
     * @description Send a signal to a specific activity within a running workflow execution.
     *
     *     This endpoint allows external systems to send arbitrary signals to
     *     activities that are waiting for external events. The activity must be
     *     designed to handle signals via the workflow's signal handler.
     *
     *     The signal is durable - if the workflow is temporarily unavailable,
     *     the signal will be delivered when it becomes available again.
     */
    post: operations['signalActivity']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * Base Resource
     * @description Foundational schema for all API resources with system-managed metadata
     */
    BaseResource: {
      /**
       * Resource ID
       * Format: uuid
       * @description Unique identifier for the resource
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      readonly id: string
      /**
       * Created At
       * Format: date-time
       * @description Timestamp when resource was created
       * @example 2025-10-09T12:00:00Z
       */
      readonly createdAt: string
      /**
       * Updated At
       * Format: date-time
       * @description Timestamp when resource was last updated
       * @example 2025-10-09T12:30:00Z
       */
      readonly updatedAt: string
      /**
       * Labels
       * @description Key-value pairs for resource labeling and filtering
       * @default {}
       * @example {
       *       "environment": "production",
       *       "region": "us-east-1",
       *       "team": "platform"
       *     }
       */
      labels?: {
        [key: string]: string
      }
    }
    NamedResource: components['schemas']['BaseResource'] & {
      /**
       * Name
       * @description Human-readable name for the resource
       * @example Authentication Service
       */
      name: string
      /**
       * Description
       * @description Detailed description of the resource
       * @example Handles user authentication and authorization workflows
       */
      description?: string | null
    }
    SoftDeletableResource: components['schemas']['BaseResource'] & {
      /**
       * Deleted At
       * Format: date-time
       * @description Timestamp when resource was soft deleted
       * @example 2025-10-09T14:00:00Z
       */
      readonly deletedAt?: string | null
      /**
       * Deleted By
       * Format: uuid
       * @description User who performed the soft delete
       * @example 660e8400-e29b-41d4-a716-446655440000
       */
      readonly deletedBy?: string | null
    }
    UserOwnedResource: components['schemas']['BaseResource'] & {
      /**
       * Created By
       * Format: uuid
       * @description User who created the resource
       * @example 770e8400-e29b-41d4-a716-446655440000
       */
      readonly createdBy: string
      /**
       * Updated By
       * Format: uuid
       * @description User who last updated the resource
       * @example 880e8400-e29b-41d4-a716-446655440000
       */
      readonly updatedBy?: string | null
    }
    Workflow: components['schemas']['NamedResource'] &
      components['schemas']['SoftDeletableResource'] &
      components['schemas']['UserOwnedResource'] & {
        /** @description Current active version number */
        current_version?: number
        /** @description Whether workflow is enabled and available for execution */
        is_enabled?: boolean
      }
    WorkflowWithVersion: components['schemas']['Workflow'] & {
      /** @description Specific version details */
      version?: {
        version?: number
        schema_version?: string
        workflow_definition?: components['schemas']['workflow-definition.schema']
        /** Format: uuid */
        created_by?: string
        /** Format: date-time */
        created_at?: string
        change_description?: string | null
      }
    }
    /**
     * Workflow Version Response
     * @description Complete details of a specific workflow version including workflow definition. Note that deleted_at and deleted_by are always null since soft-deleted versions are excluded from queries.
     */
    WorkflowVersionResponse: {
      /**
       * Format: uuid
       * @description Version unique identifier
       */
      id: string
      /**
       * Format: uuid
       * @description Parent workflow ID
       */
      workflow_id: string
      /** @description Version number */
      version: number
      /** @description YAML schema version (e.g., "1.0.0") */
      schema_version: string
      /** @description Workflow definition object conforming to workflow-definition.schema.json */
      workflow_definition: components['schemas']['workflow-definition.schema']
      /**
       * Format: uuid
       * @description User who created this version
       */
      created_by: string
      /**
       * Format: date-time
       * @description Version creation timestamp
       */
      created_at: string
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updated_at: string
      /** @description Description of changes in this version */
      change_description?: string | null
      /**
       * Format: date-time
       * @description Soft delete timestamp (always null in responses)
       */
      deleted_at?: string | null
      /**
       * Format: uuid
       * @description User who soft deleted the version (always null in responses)
       */
      deleted_by?: string | null
    }
    /**
     * Workflow Version List Response
     * @description List of workflow versions ordered by version number descending
     */
    WorkflowVersionListResponse: {
      /** @description Array of workflow versions */
      versions: components['schemas']['WorkflowVersionResponse'][]
    }
    Execution: components['schemas']['BaseResource'] & {
      /**
       * Format: uuid
       * @description ID of the workflow being executed
       */
      workflow_id?: string
      /**
       * Format: uuid
       * @description ID of the workflow version being executed
       */
      workflow_version_id?: string
      /** @description Temporal workflow execution ID */
      temporal_workflow_id?: string
      status?: components['schemas']['ExecutionStatus']
      /**
       * Format: uuid
       * @description User who started the execution
       */
      started_by?: string
      /**
       * Format: date-time
       * @description When execution transitioned from pending to running status (null if still pending)
       */
      started_at?: string | null
      /**
       * Format: date-time
       * @description When execution reached terminal state (completed, failed, or cancelled)
       */
      completed_at?: string | null
      /** @description Input parameters for the execution */
      input_data?: Record<string, never>
      /** @description Error information if execution failed */
      error_details?: string | null
      /** @description Currently executing activities */
      current_activities?: {
        activity_name?: string
        temporal_activity_id?: string
        iteration?: number | null
      }[]
      /**
       * @description Workflow definition from the executed version.
       *     Only included when requested via ?include=workflow_definition query parameter.
       *     Used for building visualization graph.
       */
      workflow_definition?: Record<string, never> | null
      /**
       * @description List of activities with their current status.
       *     Only included when requested via ?include=activities query parameter.
       *     Used for visualization of completed executions or as fallback.
       */
      activities?: components['schemas']['ActivityData'][] | null
    }
    ActivityExecution: components['schemas']['BaseResource'] & {
      /**
       * Format: uuid
       * @description Parent execution ID
       */
      execution_id?: string
      /** @description Activity ID from workflow definition */
      activity_name?: string
      /** @description Snapshot of the activity configuration from workflow definition at execution time, including executor, config, retry policy, timeout, approval settings */
      activity_definition?: Record<string, never>
      /** @description Temporal activity execution ID */
      temporal_activity_id?: string
      status?: components['schemas']['ActivityStatus']
      /**
       * Format: date-time
       * @description When activity transitioned from pending to running status (null if still pending)
       */
      started_at?: string | null
      /**
       * Format: date-time
       * @description When activity reached terminal state (completed, failed)
       */
      completed_at?: string | null
      /** @description Runtime input parameters */
      input_data?: Record<string, never>
      /** @description Activity results */
      output_data?: Record<string, never> | null
      /** @description Error information if failed */
      error_details?: string | null
      /** @description Number of retry attempts */
      retry_count?: number
      /** @description Iteration number if activity is within a loop (0-indexed) */
      iteration?: number | null
    }
    /**
     * Execution Status
     * @description Current state of a workflow execution lifecycle
     * @enum {string}
     */
    ExecutionStatus: 'pending' | 'running' | 'paused' | 'completed' | 'failed' | 'cancelled'
    /**
     * Activity Status
     * @description Current state of an individual activity execution
     * @enum {string}
     */
    ActivityStatus: 'pending' | 'running' | 'completed' | 'failed' | 'retrying' | 'skipped' | 'cancelled'
    /**
     * Create Workflow Request
     * @description Request payload for creating a new workflow from workflow definition
     */
    CreateWorkflowRequest: {
      name: string
      description?: string
      workflow_definition: components['schemas']['workflow-definition.schema']
      /**
       * @description Enable workflow for execution (defaults to true if not specified)
       * @default true
       */
      is_enabled?: boolean
    }
    /**
     * Patch Workflow Request
     * @description Request payload for updating workflow fields. Behavior depends on which fields are provided:
     *     - Metadata only (name, description, is_enabled, labels): Updates without creating new version
     *     - With workflow_definition: Validates workflow definition, compares with current version, and creates new WorkflowVersion only if definition differs (change detection)
     *
     *     Note: WorkflowVersion entities are read-only and managed automatically by the system.
     *     API accepts JSON objects for workflow_definition field.
     */
    PatchWorkflowRequest: {
      /** @description Update workflow name (metadata only, no version created) */
      name?: string
      /** @description Update workflow description (metadata only, no version created) */
      description?: string
      /** @description Enable or disable workflow for execution (metadata only, no version created) */
      is_enabled?: boolean
      /** @description Update workflow labels (metadata only, no version created) */
      labels?: {
        [key: string]: string
      }
      /** @description New workflow definition - creates new version only if definition differs from current version (change detection) */
      workflow_definition?: components['schemas']['workflow-definition.schema']
      /** @description Description of changes (used when creating new version via workflow_definition) */
      change_description?: string
    }
    /**
     * Create Execution Request
     * @description Request payload for starting a new workflow execution with optional input parameters
     */
    CreateExecutionRequest: {
      /**
       * Format: uuid
       * @description ID of the workflow to execute
       */
      workflow_id: string
      /** @description Input parameters for the workflow execution */
      input_data?: Record<string, never>
    }
    /**
     * Execution Control Request
     * @description Request payload for controlling workflow execution state (pause, resume, cancel)
     */
    ExecutionControlRequest: {
      /** @enum {string} */
      action: 'pause' | 'resume' | 'cancel'
    }
    /**
     * Activity Type
     * @description Definition of an available activity executor type with its configuration schema
     */
    ActivityType: {
      /**
       * @description Unique identifier for the executor type
       * @example agentic
       * @enum {string}
       */
      type: 'agentic' | 'connector' | 'script' | 'api' | 'approval'
      /**
       * @description Human-readable name of the executor type
       * @example Agentic Tool Execution
       */
      name: string
      /**
       * @description Detailed description of what this executor type does
       * @example Execute tasks using external agentic tool servers (MCP) with AI model integration
       */
      description: string
      /**
       * @description JSON Schema defining the valid configuration structure for this executor type
       * @example {
       *       "type": "object",
       *       "required": [
       *         "agent",
       *         "tools",
       *         "model"
       *       ],
       *       "properties": {
       *         "agent": {
       *           "type": "string",
       *           "description": "MCP server URI",
       *           "pattern": "^mcp://.+"
       *         },
       *         "tools": {
       *           "type": "array",
       *           "description": "List of tool names to invoke",
       *           "items": {
       *             "type": "string"
       *           }
       *         },
       *         "model": {
       *           "type": "string",
       *           "description": "AI model to use",
       *           "enum": [
       *             "claude-3-opus",
       *             "claude-3-sonnet",
       *             "gpt-4",
       *             "gpt-4-turbo"
       *           ]
       *         }
       *       }
       *     }
       */
      config_schema: Record<string, never>
      /**
       * @description Example configurations for this executor type
       * @example [
       *       {
       *         "name": "Sentiment Analysis",
       *         "description": "Analyze text sentiment using MCP tool",
       *         "config": {
       *           "agent": "mcp://sentiment-server",
       *           "tools": [
       *             "analyze_sentiment"
       *           ],
       *           "model": "claude-3-opus",
       *           "prompt": "Analyze the sentiment of the following text"
       *         }
       *       }
       *     ]
       */
      examples?: {
        /** @description Name of the example */
        name?: string
        /** @description What this example demonstrates */
        description?: string
        /** @description Example configuration object */
        config?: Record<string, never>
      }[]
    }
    /**
     * Approval Decision Signal
     * @description Signal payload for notifying a workflow of an approval decision.
     *     Sent by the approvals component when a user approves or rejects a request.
     */
    ApprovalDecisionSignal: {
      /**
       * Format: uuid
       * @description ID of the approval request that was decided
       */
      approval_id: string
      /** @description Activity ID of the approval node in the workflow definition */
      approval_node_id: string
      /**
       * @description Decision status from the approvals component.
       * @enum {string}
       */
      status: 'approved' | 'rejected'
      /** @description Optional notes provided with the decision */
      notes?: string | null
    }
    /**
     * Signal Response
     * @description Response confirming a signal was sent to a workflow
     */
    SignalResponse: {
      /**
       * @description Confirmation that the signal was successfully sent
       * @enum {string}
       */
      status: 'signal_sent'
      /** @description Human-readable confirmation message */
      message?: string
    }
    /**
     * Activity Signal Payload
     * @description Generic signal payload for sending arbitrary data to a specific activity
     *     within a running workflow execution.
     */
    ActivitySignalPayload: {
      /**
       * @description Arbitrary JSON data to send to the activity. The structure depends
       *     on what the activity expects to receive.
       * @example {
       *       "action": "resume",
       *       "status": "completed",
       *       "result": {
       *         "value": 42
       *       }
       *     }
       */
      signal_data: {
        [key: string]: unknown
      }
    }
    /**
     * Error Response
     * @description Standardized error response structure
     */
    Error: {
      /**
       * Error Code
       * @description Error category/code in snake_case format
       * @example validation_error
       */
      error: string
      /**
       * Error Message
       * @description Human-readable error message
       * @example The 'name' field is required
       */
      message: string
      /**
       * Error Details
       * @description Additional error details or context
       * @example Field 'name' must be between 1 and 255 characters
       */
      details?: string | null
    }
    /**
     * Paginated Response Base
     * @description Pagination metadata structure for list responses
     */
    ResourcesResponseBase: {
      /**
       * Next Page Cursor
       * @description Cursor for next page of results
       * @example eyJpZCI6InV1aWQifQ
       */
      next?: string | null
      /**
       * Previous Page Cursor
       * @description Cursor for previous page of results
       * @example eyJpZCI6InV1aWQifQ
       */
      prev?: string | null
      /**
       * Total Count
       * @description Total count of resources (only when include_total=true)
       * @example 150
       */
      total?: number | null
    }
    /** @description Manual trigger - user initiates workflow execution */
    manualTrigger: {
      /** @constant */
      type: 'manual'
      /**
       * @description Whether manual execution requires approval
       * @default false
       */
      requiresApproval?: boolean
    }
    /** @description Human approval configuration */
    approvalDefinition: {
      /** @description List of users or roles who can approve */
      approvers: string[]
      /** @description Approval prompt/question to display */
      prompt: string
      /**
       * @description Time to wait for approval in seconds
       * @example 3600
       * @example 86400
       */
      timeout?: number
      /**
       * @description Action to take if approval times out
       * @default fail
       * @enum {string}
       */
      onTimeout?: 'approve' | 'reject' | 'fail'
      /** @description Additional context to display to approvers */
      metadata?: {
        [key: string]: unknown
      }
      /** @description Output values from approval (e.g., approved, rejected, approver, timestamp) */
      outputs?: {
        /** @description Whether the approval was granted */
        approved?: boolean
        /** @description User who approved or rejected */
        approver?: string
        /** @description When approval/rejection occurred */
        timestamp?: string
        /** @description Optional comments from approver */
        comments?: string
      }
    }
    /** @description Retry configuration for failed activities */
    retryPolicy: {
      /**
       * @description Maximum number of retry attempts
       * @default 3
       */
      maxAttempts?: number
      /**
       * @description Backoff strategy between retries
       * @default exponential
       * @enum {string}
       */
      backoff?: 'fixed' | 'exponential' | 'linear'
      /**
       * @description Initial retry interval in seconds
       * @default 1
       * @example 1
       * @example 5
       * @example 10
       */
      initialInterval?: number
      /**
       * @description Maximum retry interval in seconds
       * @example 60
       * @example 300
       */
      maxInterval?: number
      /**
       * @description Backoff multiplier for exponential strategy
       * @default 2
       */
      multiplier?: number
      /**
       * @description List of error types or codes that should trigger retry
       * @example [
       *       "TIMEOUT",
       *       "NETWORK_ERROR",
       *       "RATE_LIMIT"
       *     ]
       */
      retryableErrors?: string[]
    }
    /** @description Base properties common to all activity types */
    baseActivity: {
      /** @description Unique identifier for the activity within the workflow */
      id: string
      /** @description Human-readable name for the activity */
      name?: string
      /**
       * @description Whether this activity requires human approval before execution
       * @default false
       */
      requiresApproval?: boolean
      /** @description Human approval configuration (required if requiresApproval is true) */
      approval?: components['schemas']['approvalDefinition']
      retryPolicy?: components['schemas']['retryPolicy']
      /** @description Activity timeout in seconds */
      timeout?: number
      /** @description Output schema definition for this activity */
      outputs?: {
        [key: string]: {
          /**
           * @description Expected output type
           * @enum {string}
           */
          type?: 'string' | 'number' | 'integer' | 'boolean' | 'object' | 'array'
          /** @description Description of this output */
          description?: string
        }
      }
    }
    /** @description Base properties common to all task executor types */
    baseTaskDefinition: {
      /** @description Input mapping for the task (can reference workflow inputs or previous outputs) */
      inputs?: {
        [key: string]: unknown
      }
      /** @description Output mapping from the task */
      outputs?: {
        [key: string]: string
      }
    }
    agenticTask: {
      /**
       * @description Task executor type
       * @constant
       */
      executor: 'agentic'
      config: {
        /** @description Agent identifier or MCP server endpoint */
        agent: string
        /** @description List of tools available to the agent */
        tools?: string[]
        /** @description Natural language prompt for the agent */
        prompt?: string
        /**
         * @description LLM model to use
         * @example gpt-4
         * @example claude-3-opus
         * @example gemini-pro
         */
        model?: string
      } & {
        [key: string]: unknown
      }
    } & (components['schemas']['baseTaskDefinition'] & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      executor: 'agentic'
    })
    scriptTask: {
      /**
       * @description Task executor type
       * @constant
       */
      executor: 'script'
      config: {
        /**
         * @description Script language
         * @enum {string}
         */
        language: 'python' | 'bash'
        /** @description Script code to execute */
        code: string
        /** @description Environment variables for script execution */
        environment?: {
          [key: string]: string
        }
      }
    } & (components['schemas']['baseTaskDefinition'] & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      executor: 'script'
    })
    apiTask: {
      /**
       * @description Task executor type
       * @constant
       */
      executor: 'api'
      config: {
        /**
         * @description HTTP method
         * @enum {string}
         */
        method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
        /**
         * Format: uri
         * @description API endpoint URL
         */
        url: string
        /** @description HTTP headers */
        headers?: {
          [key: string]: string
        }
        /** @description URL query parameters */
        queryParams?: {
          [key: string]: unknown
        }
        /** @description Request body (can use template expressions) */
        body?: unknown
        /** @description Authentication configuration */
        authentication?: {
          /**
           * @description Authentication type
           * @enum {string}
           */
          type: 'basic' | 'bearer' | 'apiKey' | 'oauth2'
          /** @description Reference to stored credentials */
          credentials?: string
        } & {
          [key: string]: unknown
        }
      }
    } & (components['schemas']['baseTaskDefinition'] & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      executor: 'api'
    })
    connectorTask: {
      /**
       * @description Task executor type
       * @constant
       */
      executor: 'connector'
      config: {
        /** @description Registered connector identifier */
        connectorId: string
        /** @description Operation to execute on the connector */
        operation: string
        /** @description Connector operation parameters */
        parameters?: {
          [key: string]: unknown
        }
      }
    } & (components['schemas']['baseTaskDefinition'] & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      executor: 'connector'
    })
    aapJobTemplateTask: {
      /**
       * @description Task executor type - Ansible Automation Platform Job Template
       * @constant
       */
      executor: 'aap_job_template'
      /** @description Configuration for AAP job template execution. Must specify either jobTemplateId OR both jobTemplateName and organizationName. */
      config: {
        /** @description AAP job template ID to launch (mutually exclusive with jobTemplateName/organizationName) */
        jobTemplateId?: number
        /** @description AAP job template name (requires organizationName, mutually exclusive with jobTemplateId) */
        jobTemplateName?: string
        /** @description AAP organization name (requires jobTemplateName, mutually exclusive with jobTemplateId) */
        organizationName?: string
        /** @description Override default inventory (ID only) */
        inventory?: number
        /** @description List of credential IDs to use */
        credentials?: number[]
        /** @description Extra variables to pass to the job (can use expressions like ${input.version}) */
        extraVars?: {
          [key: string]: unknown
        }
        /** @description Limit job execution to specific hosts */
        limit?: string
        /** @description Ansible tags to run (comma-separated) */
        tags?: string
        /** @description Ansible tags to skip (comma-separated) */
        skipTags?: string
        /**
         * @description Job verbosity level
         * @default 0
         */
        verbosity?: number
      } & (unknown | unknown)
    } & (components['schemas']['baseTaskDefinition'] & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      executor: 'aap_job_template'
    })
    taskDefinition:
      | components['schemas']['agenticTask']
      | components['schemas']['scriptTask']
      | components['schemas']['apiTask']
      | components['schemas']['connectorTask']
      | components['schemas']['aapJobTemplateTask']
    taskActivity: {
      /** @constant */
      type: 'task'
      /** @description Task definition */
      task: components['schemas']['taskDefinition']
    } & (components['schemas']['baseActivity'] & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'task'
    })
    activity:
      | components['schemas']['taskActivity']
      | components['schemas']['parallelActivity']
      | components['schemas']['sequenceActivity']
      | components['schemas']['conditionActivity']
      | components['schemas']['loopActivity']
      | components['schemas']['convergeActivity']
      | components['schemas']['approvalActivity']
    parallelActivity: {
      /** @constant */
      type: 'parallel'
      /** @description Activities to execute in parallel */
      branches: components['schemas']['activity'][]
    } & (components['schemas']['baseActivity'] & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'parallel'
    })
    sequenceActivity: {
      /** @constant */
      type: 'sequence'
      /** @description Activities to execute sequentially */
      steps: components['schemas']['activity'][]
    } & (components['schemas']['baseActivity'] & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'sequence'
    })
    conditionActivity: {
      /** @constant */
      type: 'condition'
      /**
       * @description Conditional expression
       * @example ${output.status == 'success'}
       * @example ${input.amount > 1000}
       */
      condition: string
      /** @description Activities to execute if condition is true */
      then: components['schemas']['activity'][]
      /** @description Activities to execute if condition is false */
      else?: components['schemas']['activity'][]
    } & (components['schemas']['baseActivity'] & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'condition'
    })
    /** @description Base properties common to all loop types */
    baseLoop: {
      /** @description Activities to execute in each iteration */
      do: components['schemas']['activity'][]
    }
    forEachLoop: {
      /** @constant */
      type: 'forEach'
      /**
       * @description Expression referencing array to iterate over
       * @example ${input.users}
       * @example ${output.results}
       */
      items: string
      /**
       * @description Variable name for current item
       * @default item
       */
      itemVariable?: string
      /**
       * @description Variable name for current index
       * @default index
       */
      indexVariable?: string
    } & (components['schemas']['baseLoop'] & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'forEach'
    })
    whileLoop: {
      /** @constant */
      type: 'while'
      /**
       * @description Condition expression to evaluate before each iteration
       * @example ${counter < 10}
       * @example ${!completed}
       */
      condition: string
      /**
       * @description Maximum number of iterations to prevent infinite loops
       * @default 1000
       */
      maxIterations?: number
    } & (components['schemas']['baseLoop'] & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'while'
    })
    loopDefinition: components['schemas']['forEachLoop'] | components['schemas']['whileLoop']
    loopActivity: {
      /** @constant */
      type: 'loop'
      /** @description Loop definition */
      loop: components['schemas']['loopDefinition']
    } & (components['schemas']['baseActivity'] & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'loop'
    })
    /** @description Converge pattern configuration - waits for specific activities to complete before proceeding */
    convergeDefinition: {
      /** @description List of activity IDs to wait for */
      branches: string[]
      /**
       * @description Converge strategy: 'all' waits for all specified branches
       * @default all
       * @enum {string}
       */
      strategy?: 'all'
      /**
       * @description Maximum time to wait for converge condition in seconds
       * @example 300
       * @example 1800
       * @example 3600
       */
      timeout?: number
      /**
       * @description Action to take if timeout is reached before converge condition is met
       * @default fail
       * @enum {string}
       */
      onTimeout?: 'continue' | 'fail'
      /**
       * @description Whether to aggregate outputs from completed branches into an object keyed by activity ID
       * @default true
       */
      aggregateOutputs?: boolean
    }
    convergeActivity: {
      /** @constant */
      type: 'converge'
      /** @description Converge definition */
      converge: components['schemas']['convergeDefinition']
    } & (components['schemas']['baseActivity'] & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'converge'
    })
    /** @description Human approval node - pauses branch execution until approved or rejected */
    approvalActivity: {
      /** @constant */
      type: 'approval'
      /** @description Detailed context/prompt for approvers explaining what they are approving */
      description?: string
      /** @description Activities to execute when approval is granted */
      onApproved: components['schemas']['activity'][]
      /** @description Activities to execute when approval is rejected or expires */
      onRejected?: components['schemas']['activity'][]
    } & (components['schemas']['baseActivity'] & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'approval'
    })
    /**
     * Workflow Definition Schema
     * @description JSON Schema for workflow YAML definitions in the Nexus Workflow Engine
     */
    'workflow-definition.schema': {
      /**
       * @description Schema version that this workflow definition conforms to (semver format)
       * @example 1.0.0
       * @example 1.1.0
       * @example 2.0.0
       */
      schemaVersion: string
      /**
       * @description Workflow definition version number (increments with each change)
       * @example 1
       * @example 2
       * @example 3
       */
      version: number
      /** @description Workflow metadata and configuration */
      metadata: {
        /** @description Unique name for the workflow */
        name: string
        /** @description Human-readable description of the workflow purpose */
        description: string
        /** @description Tags for categorization and search */
        tags?: string[]
        /** @description User or team responsible for the workflow */
        owner?: string
        /**
         * @description Maximum workflow execution time in seconds - applies to entire workflow
         * @example 3600
         * @example 86400
         * @example 1800
         */
        timeout?: number
      }
      /** @description Workflow trigger configuration - manual trigger only */
      triggers?: components['schemas']['manualTrigger'][]
      /** @description Input parameter definitions for the workflow */
      inputs?: {
        [key: string]: definitions['parameter']
      }
      /** @description Workflow-level variables that can be referenced throughout the workflow */
      variables?: {
        [key: string]: string | number | boolean | null | Record<string, never> | unknown[]
      }
      /** @description Secret references for credentials and sensitive data (values stored securely, not in workflow definition) */
      secrets?: {
        [key: string]: {
          /** @description Reference to secret stored in secret manager */
          secretId: string
          /**
           * @description Type of secret for validation
           * @default custom
           * @enum {string}
           */
          type?: 'api_key' | 'bearer_token' | 'basic_auth' | 'oauth2' | 'custom'
        }
      }
      /** @description The workflow execution definition */
      workflow: {
        /** @description List of activities to execute in the workflow */
        activities: components['schemas']['activity'][]
      }
    }
    /**
     * Activity Data
     * @description Activity data for execution response when include=activities is requested
     */
    ActivityData: {
      /**
       * @description Activity ID from workflow definition
       * @example process_data
       */
      activity_id: string
      status: components['schemas']['ActivityStatus']
      /**
       * @description Error message if status is failed
       * @example Connection timeout to external service
       */
      error_details?: string | null
      /**
       * Format: date-time
       * @description When activity started execution
       * @example 2025-12-10T15:00:10Z
       */
      started_at?: string | null
      /**
       * Format: date-time
       * @description When activity completed
       * @example 2025-12-10T15:00:15Z
       */
      completed_at?: string | null
    }
  }
  responses: never
  parameters: {
    /**
     * @description Number of resources to return per page
     * @example 20
     */
    limitParam: number
    /**
     * @description Opaque cursor for pagination (from previous response)
     * @example eyJpZCI6InV1aWQifQ
     */
    cursorParam: string
    /**
     * @description Whether to include total count in response (may impact performance)
     * @example true
     */
    includeTotalParam: boolean
    /**
     * @description Sort order for resources.
     *     - Ascending: `field` (e.g., `name`)
     *     - Descending: `-field` (e.g., `-created_at`)
     * @example -created_at
     */
    sortParam: string
    /**
     * @description Filter resources by name.
     *     - Exact match: `name=value`
     *     - Contains: `name[contains]=value`
     * @example auth
     */
    nameFilterParam: string & {
      /**
       * Contains
       * @description Substring to match within the name (case-insensitive). ?name[contains]=<substring>
       */
      contains?: string
      /**
       * Starts With
       * @description Prefix to match at the start of the name (case-insensitive). ?name[starts_with]=<prefix>
       */
      starts_with?: string
      /**
       * Equals
       * @description Exact match of the name (case-insensitive). ?name[eq]=<name>
       */
      eq?: string
      /**
       * Greater Than
       * @description Greater than comparison (lexicographical). ?name[gt]=<name>
       */
      gt?: string
      /**
       * Greater Than Or Equal
       * @description Greater than or equal comparison (lexicographical). ?name[gte]=<name>
       */
      gte?: string
      /**
       * Less Than
       * @description Less than comparison (lexicographical). ?name[lt]=<name>
       */
      lt?: string
      /**
       * Less Than Or Equal
       * @description Less than or equal comparison (lexicographical). ?name[lte]=<name>
       */
      lte?: string
    }
    createdAtFilterParam: string & {
      /**
       * Equals
       * Format: date-time
       * @description Exact match of creation timestamp. ?created_at[eq]=<timestamp>
       */
      eq?: string
      /**
       * Greater Than
       * Format: date-time
       * @description Greater than comparison. ?created_at[gt]=<timestamp>
       */
      gt?: string
      /**
       * Greater Than Or Equal
       * Format: date-time
       * @description Greater than or equal comparison. ?created_at[gte]=<timestamp>
       */
      gte?: string
      /**
       * Less Than
       * Format: date-time
       * @description Less than comparison. ?created_at[lt]=<timestamp>
       */
      lt?: string
      /**
       * Less Than Or Equal
       * Format: date-time
       * @description Less than or equal comparison. ?created_at[lte]=<timestamp>
       */
      lte?: string
    }
    updatedAtFilterParam: string & {
      /**
       * Equals
       * Format: date-time
       * @description Exact match of last update timestamp. ?updated_at[eq]=<timestamp>
       */
      eq?: string
      /**
       * Greater Than
       * Format: date-time
       * @description Greater than comparison. ?updated_at[gt]=<timestamp>
       */
      gt?: string
      /**
       * Greater Than Or Equal
       * Format: date-time
       * @description Greater than or equal comparison. ?updated_at[gte]=<timestamp>
       */
      gte?: string
      /**
       * Less Than
       * Format: date-time
       * @description Less than comparison. ?updated_at[lt]=<timestamp>
       */
      lt?: string
      /**
       * Less Than Or Equal
       * Format: date-time
       * @description Less than or equal comparison. ?updated_at[lte]=<timestamp>
       */
      lte?: string
    }
    /**
     * @description Filter resources by label key-value pairs.
     *     - Single label: `labels[environment]=production`
     *     - Multiple labels: `labels[environment]=production&labels[region]=us-east-1`
     *     All specified labels must match (AND logic).
     * @example {
     *       "environment": "production",
     *       "region": "us-east-1"
     *     }
     */
    labelsFilterParam: {
      [key: string]: string
    }
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  signalApprovalDecision: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Execution ID of the workflow awaiting approval */
        executionId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ApprovalDecisionSignal']
      }
    }
    responses: {
      /** @description Signal sent successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SignalResponse']
        }
      }
      /** @description Execution not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /**
       * @description Execution is not in a state that can receive approval signals
       *     (e.g., already completed, cancelled, or not waiting for approval)
       */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
  signalActivity: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Execution ID of the running workflow */
        execution_id: string
        /** @description Activity ID from the workflow definition */
        activity_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivitySignalPayload']
      }
    }
    responses: {
      /** @description Signal sent successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SignalResponse']
        }
      }
      /** @description Execution not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Failed to send signal */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      /** @description Temporal workflow engine unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
    }
  }
}
