"""add audit read policy

Revision ID: 20e24d4b47f4
Revises: 68655cddfd4f
Create Date: 2026-04-14 15:50:39.838103

"""

from collections.abc import Sequence

from nexus.authz.migration_ops import PolicyAdd, RolePolicyAppend, apply_policy_ops, revert_policy_ops

# revision identifiers, used by Alembic.
revision: str = "20e24d4b47f4"
down_revision: str | Sequence[str] | None = "68655cddfd4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    apply_policy_ops(
        [
            PolicyAdd(
                "audit:read:any", "Read any audit", [{"effect": "allow", "actions": ["audit:read"], "scope": "any"}]
            ),
            RolePolicyAppend("admin", "audit:read:any"),
            RolePolicyAppend("auditor", "audit:read:any"),
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    revert_policy_ops(
        [
            PolicyAdd(
                "audit:read:any", "Read any audit", [{"effect": "allow", "actions": ["audit:read"], "scope": "any"}]
            ),
            RolePolicyAppend("admin", "audit:read:any"),
            RolePolicyAppend("auditor", "audit:read:any"),
        ]
    )
    # ### end Alembic commands ###
