"""add model_name to invocations

Revision ID: c4a5b6d7e8f9
Revises: ff2dde768eeb
Create Date: 2026-04-02 14:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4a5b6d7e8f9"
down_revision: str | Sequence[str] | None = "ff2dde768eeb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invocations", sa.Column("model_name", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_invocations_model_name"), "invocations", ["model_name"], unique=False)
    # ### end Alembic commands ###

    # CUSTOM: Backfill model_name from result JSONB field
    op.execute(
        sa.text(
            """
            UPDATE invocations
            SET model_name = result -> 'response_metadata' ->> 'model'
            WHERE result IS NOT NULL
              AND result -> 'response_metadata' ->> 'model' IS NOT NULL
            """
        )
    )
    # END CUSTOM


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invocations_model_name"), table_name="invocations")
    op.drop_column("invocations", "model_name")
    # ### end Alembic commands ###
