"""add user_idp_groups and idp_group_mapping_entries tables

Revision ID: c7f5bef51f16
Revises: a6a0d8d0ef9a
Create Date: 2026-04-15 19:56:30.700791

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7f5bef51f16"
down_revision: str | Sequence[str] | None = "a6a0d8d0ef9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idp_group_mapping_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("identity_provider_id", sa.Uuid(), nullable=False),
        sa.Column("idp_group_value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nexus_group_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["identity_provider_id"],
            ["identity_providers.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["nexus_group_id"],
            ["groups.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_provider_id", "idp_group_value"),
    )
    op.create_index(
        op.f("ix_idp_group_mapping_entries_identity_provider_id"),
        "idp_group_mapping_entries",
        ["identity_provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idp_group_mapping_entries_nexus_group_id"),
        "idp_group_mapping_entries",
        ["nexus_group_id"],
        unique=False,
    )
    op.create_table(
        "user_idp_groups",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("identity_provider_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["identity_provider_id"], ["identity_providers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "identity_provider_id", "group_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_idp_groups")
    op.drop_index(op.f("ix_idp_group_mapping_entries_nexus_group_id"), table_name="idp_group_mapping_entries")
    op.drop_index(op.f("ix_idp_group_mapping_entries_identity_provider_id"), table_name="idp_group_mapping_entries")
    op.drop_table("idp_group_mapping_entries")
    # ### end Alembic commands ###
