"""add unique constraint on credential_type name

Revision ID: f3a1b2c4d5e6
Revises: 4ab8d1a4bf66
Create Date: 2026-04-17 00:00:00.000000

Fixes AAP-72262: preseed_credential_types() crashes with
MultipleResultsFound when duplicate rows exist because the name
column had only a non-unique index.

This migration:
1. Reassigns credentials from duplicate rows to the survivor (oldest per name).
2. Deletes duplicate rows.
3. Replaces the non-unique index with a unique index on name.

CredentialType does not support soft delete (extends BaseResource, not
SoftDeletableResource), so a plain unique constraint is used instead
of a partial index with deleted_at filter.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3a1b2c4d5e6"
down_revision: str = "4ab8d1a4bf66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:  # noqa: D103
    # CUSTOM: Deduplicate existing rows before adding unique constraint.
    # Reassign credentials to the survivor row, then delete duplicates.
    # Keeps the row with the earliest created_at per name (the "survivor").
    # Uses id as tiebreaker for deterministic selection when created_at ties.
    op.execute("""
        WITH survivors AS (
            SELECT DISTINCT ON (name) id, name
            FROM credential_types
            ORDER BY name, created_at ASC, id ASC
        )
        UPDATE credentials
        SET credential_type_id = survivors.id
        FROM credential_types AS ct
        JOIN survivors ON survivors.name = ct.name
        WHERE credentials.credential_type_id = ct.id
          AND ct.id != survivors.id
    """)
    op.execute("""
        DELETE FROM credential_types
        WHERE id NOT IN (
            SELECT DISTINCT ON (name) id
            FROM credential_types
            ORDER BY name, created_at ASC, id ASC
        )
    """)
    # END CUSTOM

    # Drop the old non-unique index and replace with unique
    op.drop_index("ix_credential_types_name", table_name="credential_types")

    # ### commands auto generated by Alembic ###

    op.create_index(
        op.f("ix_credential_types_name"),
        "credential_types",
        ["name"],
        unique=True,
    )

    # ### end Alembic commands ###


def downgrade() -> None:  # noqa: D103
    # ### commands auto generated by Alembic ###

    # Restore the original non-unique index
    op.drop_index(op.f("ix_credential_types_name"), table_name="credential_types")
    op.create_index(
        op.f("ix_credential_types_name"),
        "credential_types",
        ["name"],
        unique=False,
    )

    # ### end Alembic commands ###
