import type { ToolProvider } from '@ansible/nexus-contracts'
import { ProviderStatusEnum } from '@ansible/nexus-contracts'

export const providers: ToolProvider[] = [
  {
    id: '1',
    name: 'GitHub Copilot',
    status: ProviderStatusEnum.AVAILABLE,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.github.com',
      api_key: null,
    },
    tool_count: 5,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Slack Bot',
    status: ProviderStatusEnum.AVAILABLE,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.slack.com',
      api_key: null,
    },
    tool_count: 8,
    created_at: '2024-01-16T11:00:00Z',
    updated_at: '2024-01-16T11:00:00Z',
  },
  {
    id: '3',
    name: 'Jira Integration',
    status: ProviderStatusEnum.ERROR,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.atlassian.com',
      api_key: null,
    },
    tool_count: 12,
    created_at: '2024-01-17T12:00:00Z',
    updated_at: '2024-01-17T12:00:00Z',
  },
  {
    id: '4',
    name: 'ServiceNow',
    status: ProviderStatusEnum.VALIDATING,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.servicenow.com',
      api_key: null,
    },
    tool_count: 15,
    created_at: '2024-01-18T13:00:00Z',
    updated_at: '2024-01-18T13:00:00Z',
  },
  {
    id: '5',
    name: 'PagerDuty',
    status: ProviderStatusEnum.AVAILABLE,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.pagerduty.com',
      api_key: null,
    },
    tool_count: 6,
    created_at: '2024-01-19T14:00:00Z',
    updated_at: '2024-01-19T14:00:00Z',
  },
  {
    id: '6',
    name: 'Datadog Monitor',
    status: ProviderStatusEnum.AVAILABLE,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.datadoghq.com',
      api_key: null,
    },
    tool_count: 10,
    created_at: '2024-01-20T15:00:00Z',
    updated_at: '2024-01-20T15:00:00Z',
  },
  {
    id: '7',
    name: 'Splunk',
    status: ProviderStatusEnum.ERROR,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.splunk.com',
      api_key: null,
    },
    tool_count: 20,
    created_at: '2024-01-21T16:00:00Z',
    updated_at: '2024-01-21T16:00:00Z',
  },
  {
    id: '8',
    name: 'Prometheus',
    status: ProviderStatusEnum.VALIDATING,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.prometheus.io',
      api_key: null,
    },
    tool_count: 7,
    created_at: '2024-01-22T17:00:00Z',
    updated_at: '2024-01-22T17:00:00Z',
  },
  {
    id: '9',
    name: 'Grafana',
    status: ProviderStatusEnum.AVAILABLE,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.grafana.com',
      api_key: null,
    },
    tool_count: 9,
    created_at: '2024-01-23T18:00:00Z',
    updated_at: '2024-01-23T18:00:00Z',
  },
  {
    id: '10',
    name: 'Terraform Cloud',
    status: ProviderStatusEnum.ERROR,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.terraform.io',
      api_key: null,
    },
    tool_count: 18,
    created_at: '2024-01-24T19:00:00Z',
    updated_at: '2024-01-24T19:00:00Z',
  },
  {
    id: '11',
    name: 'Jenkins',
    status: ProviderStatusEnum.AVAILABLE,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.jenkins.io',
      api_key: null,
    },
    tool_count: 14,
    created_at: '2024-01-25T10:00:00Z',
    updated_at: '2024-01-25T10:00:00Z',
  },
  {
    id: '12',
    name: 'GitLab',
    status: ProviderStatusEnum.AVAILABLE,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.gitlab.com',
      api_key: null,
    },
    tool_count: 11,
    created_at: '2024-01-26T11:00:00Z',
    updated_at: '2024-01-26T11:00:00Z',
  },
  {
    id: '13',
    name: 'Ansible Automation Platform',
    status: ProviderStatusEnum.VALIDATING,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.ansible.com',
      api_key: null,
    },
    tool_count: 25,
    created_at: '2024-01-27T12:00:00Z',
    updated_at: '2024-01-27T12:00:00Z',
  },
  {
    id: '14',
    name: 'Azure DevOps',
    status: ProviderStatusEnum.ERROR,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.azure.com',
      api_key: null,
    },
    tool_count: 16,
    created_at: '2024-01-28T13:00:00Z',
    updated_at: '2024-01-28T13:00:00Z',
  },
  {
    id: '15',
    name: 'AWS CloudWatch',
    status: ProviderStatusEnum.AVAILABLE,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.aws.amazon.com',
      api_key: null,
    },
    tool_count: 22,
    created_at: '2024-01-29T14:00:00Z',
    updated_at: '2024-01-29T14:00:00Z',
  },
  {
    id: '16',
    name: 'New Relic',
    status: ProviderStatusEnum.VALIDATING,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.newrelic.com',
      api_key: null,
    },
    tool_count: 13,
    created_at: '2024-01-30T15:00:00Z',
    updated_at: '2024-01-30T15:00:00Z',
  },
  {
    id: '17',
    name: 'Dynatrace',
    status: ProviderStatusEnum.AVAILABLE,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.dynatrace.com',
      api_key: null,
    },
    tool_count: 17,
    created_at: '2024-01-31T16:00:00Z',
    updated_at: '2024-01-31T16:00:00Z',
  },
  {
    id: '18',
    name: 'Elastic Stack',
    status: ProviderStatusEnum.ERROR,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.elastic.co',
      api_key: null,
    },
    tool_count: 19,
    created_at: '2024-02-01T17:00:00Z',
    updated_at: '2024-02-01T17:00:00Z',
  },
  {
    id: '19',
    name: 'Kubernetes',
    status: ProviderStatusEnum.AVAILABLE,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.kubernetes.io',
      api_key: null,
    },
    tool_count: 30,
    created_at: '2024-02-02T18:00:00Z',
    updated_at: '2024-02-02T18:00:00Z',
  },
  {
    id: '20',
    name: 'OpenShift',
    status: ProviderStatusEnum.VALIDATING,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.openshift.com',
      api_key: null,
    },
    tool_count: 28,
    created_at: '2024-02-03T19:00:00Z',
    updated_at: '2024-02-03T19:00:00Z',
  },
  {
    id: '21',
    name: 'Docker Hub',
    status: ProviderStatusEnum.AVAILABLE,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.docker.com',
      api_key: null,
    },
    tool_count: 8,
    created_at: '2024-02-04T20:00:00Z',
    updated_at: '2024-02-04T20:00:00Z',
  },
  {
    id: '22',
    name: 'HashiCorp Vault',
    status: ProviderStatusEnum.ERROR,
    configuration: {
      provider_type: 'mcp',
      base_url: 'https://mcp.vaultproject.io',
      api_key: null,
    },
    tool_count: 12,
    created_at: '2024-02-05T21:00:00Z',
    updated_at: '2024-02-05T21:00:00Z',
  },
]
