import type * as IntegrationsAPI from '@ansible/nexus-contracts/src/integrations-api.js'
import { mockDate } from './mockDates'

type LLMModelRead = IntegrationsAPI.components['schemas']['LLMModelRead']

export const models: LLMModelRead[] = [
  // Integration '10' — Red Hat AI
  {
    id: 'model-1',
    integration_id: '10',
    model_id: 'granite-3.3-8b-instruct',
    name: 'granite-3.3-8b-instruct',
    description: '128k context',
    enabled: true,
    is_default: true,
    last_refreshed_at: mockDate.daysAgo1,
    created_at: mockDate.daysAgo5,
    updated_at: mockDate.daysAgo1,
  },
  {
    id: 'model-2',
    integration_id: '10',
    model_id: 'granite-3.3-2b-instruct',
    name: 'granite-3.3-2b-instruct',
    description: '128k context',
    enabled: true,
    is_default: false,
    last_refreshed_at: mockDate.daysAgo1,
    created_at: mockDate.daysAgo5,
    updated_at: mockDate.daysAgo1,
  },
  {
    id: 'model-3',
    integration_id: '10',
    model_id: 'granite-code-8b',
    name: 'granite-code-8b',
    description: '8k context',
    enabled: true,
    is_default: false,
    last_refreshed_at: mockDate.daysAgo1,
    created_at: mockDate.daysAgo5,
    updated_at: mockDate.daysAgo1,
  },
  {
    id: 'model-4',
    integration_id: '10',
    model_id: 'granite-3.1-8b-instruct',
    name: 'granite-3.1-8b-instruct',
    description: '128k context',
    enabled: false,
    is_default: false,
    last_refreshed_at: mockDate.daysAgo1,
    created_at: mockDate.daysAgo5,
    updated_at: mockDate.daysAgo2,
  },
  {
    id: 'model-5',
    integration_id: '10',
    model_id: 'granite-guardian-8b',
    name: 'granite-guardian-8b',
    description: 'Safety model for content filtering',
    enabled: false,
    is_default: false,
    last_refreshed_at: mockDate.daysAgo1,
    created_at: mockDate.daysAgo5,
    updated_at: mockDate.daysAgo2,
  },

  // Integration '11' — OpenAI Production
  {
    id: 'model-6',
    integration_id: '11',
    model_id: 'gpt-4o',
    name: 'gpt-4o',
    description: '128k context',
    enabled: true,
    is_default: true,
    last_refreshed_at: mockDate.daysAgo1,
    created_at: mockDate.daysAgo4,
    updated_at: mockDate.daysAgo1,
  },
  {
    id: 'model-7',
    integration_id: '11',
    model_id: 'gpt-4o-mini',
    name: 'gpt-4o-mini',
    description: '128k context',
    enabled: true,
    is_default: false,
    last_refreshed_at: mockDate.daysAgo1,
    created_at: mockDate.daysAgo4,
    updated_at: mockDate.daysAgo1,
  },
  {
    id: 'model-8',
    integration_id: '11',
    model_id: 'gpt-3.5-turbo',
    name: 'gpt-3.5-turbo',
    description: '16k context',
    enabled: true,
    is_default: false,
    last_refreshed_at: mockDate.daysAgo1,
    created_at: mockDate.daysAgo4,
    updated_at: mockDate.daysAgo1,
  },
  {
    id: 'model-9',
    integration_id: '11',
    model_id: 'o3-mini',
    name: 'o3-mini',
    description: '200k context',
    enabled: true,
    is_default: false,
    last_refreshed_at: mockDate.daysAgo1,
    created_at: mockDate.daysAgo4,
    updated_at: mockDate.daysAgo1,
  },
  {
    id: 'model-10',
    integration_id: '11',
    model_id: 'gpt-4-turbo',
    name: 'gpt-4-turbo',
    description: '128k context',
    enabled: false,
    is_default: false,
    last_refreshed_at: mockDate.daysAgo1,
    created_at: mockDate.daysAgo4,
    updated_at: mockDate.daysAgo2,
  },
  {
    id: 'model-11',
    integration_id: '11',
    model_id: 'o1-mini',
    name: 'o1-mini',
    description: '128k context',
    enabled: false,
    is_default: false,
    last_refreshed_at: mockDate.daysAgo1,
    created_at: mockDate.daysAgo4,
    updated_at: mockDate.daysAgo2,
  },
  {
    id: 'model-12',
    integration_id: '11',
    model_id: 'o1',
    name: 'o1',
    description: '200k context',
    enabled: false,
    is_default: false,
    last_refreshed_at: mockDate.daysAgo1,
    created_at: mockDate.daysAgo4,
    updated_at: mockDate.daysAgo3,
  },
  {
    id: 'model-13',
    integration_id: '11',
    model_id: 'gpt-4',
    name: 'gpt-4',
    description: '8k context',
    enabled: false,
    is_default: false,
    last_refreshed_at: mockDate.daysAgo1,
    created_at: mockDate.daysAgo4,
    updated_at: mockDate.daysAgo3,
  },
]
