apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/syntara-orchestration/syntara-ui?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch.startsWith("refs/tags/")
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: ansible-automation-orchestrator-stable
    appstudio.openshift.io/component: ansible-automation-orchestrator-ui-stable
    pipelines.appstudio.openshift.io/type: build
  name: ansible-automation-orchestrator-ui-stable-on-tag
  namespace: nexus-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/nexus-tenant/ansible-automation-platform/automation-orchestrator-ui-rhel9:{{revision}}
  - name: dockerfile
    value: packages/nexus-ui/Containerfile.konflux
  - name: path-context
    value: .
  - name: build-platforms
    value:
      - linux/x86_64
      - linux/arm64
  - name: hermetic
    value: 'true'
  - name: prefetch-input
    value: '{"type": "npm", "path": "."}'
  pipelineRef:
    params:
    - name: name
      value: pde-docker-build-multi-platform-oci-ta
    - name: bundle
      value: quay.io/aap-ci/pde-docker-build-multi-platform-oci-ta-bundle@sha256:2f761cfb1889654460758f74b7cc1157877b91721f1da283923db55fad173fbd
    - name: kind
      value: pipeline
    resolver: bundles
  taskRunTemplate:
    serviceAccountName: build-pipeline-ansible-automation-orchestrator-ui-stable
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
