---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/syntara-orchestration/syntara?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: "{{revision}}"
    build.appstudio.redhat.com/target_branch: "{{target_branch}}"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      event == "push" && target_branch == "devel" &&
      (files.all.exists(x, x.startsWith("backend/")) ||
      ".tekton/ansible-automation-orchestrator-backend-devel-push.yaml".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: ansible-automation-orchestrator-devel
    appstudio.openshift.io/component: ansible-automation-orchestrator-backend-devel
    pipelines.appstudio.openshift.io/type: build
  name: ansible-automation-orchestrator-backend-devel-on-push
  namespace: nexus-tenant
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: quay.io/redhat-user-workloads/nexus-tenant/ansible-automation-platform/automation-orchestrator-backend-rhel9:{{revision}}
    - name: dockerfile
      value: backend/containers/nexus/Containerfile
    - name: path-context
      value: backend
    - name: build-args
      value:
        - CONTAINER_IMAGE_VERSION={{revision}}
        - DOWNSTREAM_OVERRIDE=quay.io/redhat-user-workloads/nexus-tenant/ansible-automation-platform/automation-orchestrator-downstream-override@sha256:af90c3824339a47b1acafb4fd974670d2f17e79826b6b3904615ee6b9891ef77
        - BRANDING=true
    - name: build-platforms
      value:
        - linux-c8xlarge/amd64
        - linux-c8xlarge/arm64
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: '[{"type": "pip", "path": "backend"}, {"type": "rpm", "path": "backend"}, {"type": "generic", "path": "backend"}]'
    - name: prefetch-mode
      value: permissive
    - name: additional-secret
      value: nexus-segment-write-keys
  pipelineRef:
    params:
      - name: name
        value: container
      - name: bundle
        value: quay.io/aap-ci/tekton-catalog/pipeline/build/container:0.2@sha256:c7436f23e24b0e383eb60ea4d1601d69c1c596035f8ab0402226ada75ac112a4
      - name: kind
        value: pipeline
      - name: secret
        value: quay-aap-ci-viewer
    resolver: bundles
  taskRunTemplate:
    serviceAccountName: build-pipeline-ansible-automation-orchestrator-backend-devel
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
status: {}
