"""Contains all the data models used in inputs/outputs."""

from __future__ import annotations

import importlib
import re
from pathlib import Path
from typing import Any

__all__ = (
    "AAPCredential",
    "AAPExecutionEnvironment",
    "AAPInstanceGroup",
    "AAPInventory",
    "AAPJobTemplate",
    "AAPJobTemplateDetail",
    "AAPJobType",
    "AAPLabel",
    "AAPListResponseAAPCredential",
    "AAPListResponseAAPExecutionEnvironment",
    "AAPListResponseAAPInstanceGroup",
    "AAPListResponseAAPInventory",
    "AAPListResponseAAPJobTemplate",
    "AAPListResponseAAPLabel",
    "AAPListResponseAAPOrganization",
    "AAPListResponseAAPWorkflowJobTemplate",
    "AAPOrganization",
    "AAPSummaryField",
    "AAPWorkflowJobTemplate",
    "AAPWorkflowJobTemplateDetail",
    "AccessTokenResponse",
    "ActivityData",
    "ActivityDataOutputDataType0",
    "ActivityExecution",
    "ActivityExecutionActivityDefinitionType0",
    "ActivityExecutionInputData",
    "ActivityExecutionLabels",
    "ActivityExecutionListResponse",
    "ActivityExecutionOutputDataType0",
    "ActivitySignalPayload",
    "ActivitySignalPayloadSignalData",
    "ActivityStatus",
    "ActivitySummary",
    "ActorType",
    "ApprovalCreateRequest",
    "ApprovalDecisionRequest",
    "ApprovalDecisionStatus",
    "ApprovalListResponse",
    "ApprovalRequestRead",
    "ApprovalRequestReadLabels",
    "ApprovalRequestStatus",
    "AuditContextData",
    "AuditEventListResponse",
    "AuditEventRead",
    "AuditEventReadLabels",
    "AuthProviderInfo",
    "AuthProvidersResponse",
    "AuthType",
    "BatchApprovalDecision",
    "BatchApprovalDecisionStatus",
    "BatchApprovalRequest",
    "BatchApprovalResponse",
    "BatchApprovalResult",
    "BulkUpdateToolsResponseBulkUpdateTools",
    "CanIRequest",
    "CanIRequestResourceLabels",
    "CanIRequestResourceMetadata",
    "CanIResponse",
    "CategoriesListResponse",
    "ComponentKPISummary",
    "ComponentKPISummaryMetrics",
    "ComponentKPISummaryMetricsAdditionalPropertyType1",
    "CreateExampleRequest",
    "CredentialCreate",
    "CredentialCreateInputs",
    "CredentialCreateLabels",
    "CredentialListResponse",
    "CredentialPatch",
    "CredentialPatchInputsType0",
    "CredentialPatchLabelsType0",
    "CredentialRead",
    "CredentialReadInputs",
    "CredentialReadLabels",
    "CredentialTypeListResponse",
    "CredentialTypeRead",
    "CredentialTypeReadInjectors",
    "CredentialTypeReadInputs",
    "CredentialTypeReadLabels",
    "CredentialWorkflowRef",
    "CsrfTokenResponse",
    "CurrentActivity",
    "DeleteResponse",
    "ErrorData",
    "EventCategory",
    "EventSeverity",
    "EventStatus",
    "ExampleItem",
    "ExampleListResponse",
    "ExampleStatus",
    "ExecutionCreate",
    "ExecutionCreateInputData",
    "ExecutionListResponse",
    "ExecutionMode",
    "ExecutionRead",
    "ExecutionReadExecutionMetadataType0",
    "ExecutionReadInputData",
    "ExecutionReadLabels",
    "ExecutionStatus",
    "FileStatus",
    "FileUploadInfo",
    "FileUploadResponse",
    "GlobalRevocationTimestampRead",
    "GroupCreate",
    "GroupDirectoryEntry",
    "GroupMemberAdd",
    "GroupMemberAddResponse",
    "GroupMemberRead",
    "GroupRead",
    "GroupReadLabels",
    "GroupUpdate",
    "IdentityProviderCreate",
    "IdentityProviderListResponse",
    "IdentityProviderPatch",
    "IdentityProviderResponse",
    "IdentityProviderResponseLabels",
    "Invocation",
    "InvocationCancelRequest",
    "InvocationCancelResponse",
    "InvocationCheckpointDataType0",
    "InvocationContextData",
    "InvocationCreateRequest",
    "InvocationCreateRequestContextdata",
    "InvocationLabels",
    "InvocationListResponse",
    "InvocationRequestWithFile",
    "InvocationResultType0",
    "InvocationStatus",
    "KPIDashboard",
    "LoginRequest",
    "MCPConfiguration",
    "MembershipSource",
    "MetricRecord",
    "MetricRecordLabels",
    "MetricsCategoryType",
    "MetricsRecordPage",
    "MetricsStoreSummary",
    "MetricsStoreSummaryCounters",
    "MetricsStoreSummaryMetricTypeCounts",
    "MetricType",
    "OidcAuthorizeFlowType0",
    "OIDCClaimMapping",
    "OIDCConfiguration",
    "OIDCConfigurationPatch",
    "OIDCConfigurationResponse",
    "OIDCGroupMappingEntry",
    "OIDCTestRequest",
    "OIDCTestResult",
    "OIDCTestResultClaimAliasesType0",
    "OIDCTestResultMetadataType0",
    "PercentileStats",
    "PermissionEntry",
    "PolicyCreate",
    "PolicyCreateLabels",
    "PolicyListResponse",
    "PolicyRead",
    "PolicyReadLabels",
    "PolicyReadStatementsItem",
    "PolicyStatementSchema",
    "PolicyStatementSchemaConditionsType0",
    "PolicyUpdate",
    "PolicyUpdateLabelsType0",
    "PreResolvedNodeOutput",
    "PreResolvedNodeOutputControlType0",
    "PreResolvedNodeOutputOutput",
    "PreviousStepContext",
    "PreviousStepContextOutputType0",
    "PrincipalType",
    "ProjectCreate",
    "ProjectCreateLabels",
    "ProjectCredentialCreate",
    "ProjectCredentialCreateInputs",
    "ProjectCredentialCreateLabels",
    "ProjectListResponse",
    "ProjectPolicyCreate",
    "ProjectPolicyCreateLabels",
    "ProjectRead",
    "ProjectReadLabels",
    "ProjectRoleCreate",
    "ProjectRoleCreateLabels",
    "ProjectUpdate",
    "ProjectUpdateLabelsType0",
    "ProviderStatus",
    "PublishVersionRequest",
    "ResetInternalMetricsStoreResponseResetInternalMetricsStore",
    "ResourceActionsResponse",
    "ResourceActionsResponseResourceActions",
    "ResourcesResponseGroupDirectoryEntry",
    "ResourcesResponseGroupMemberRead",
    "ResourcesResponseGroupRead",
    "ResourcesResponseUserDirectoryEntry",
    "ResourcesResponseUserGroupRead",
    "ResourcesResponseUserRead",
    "RevocationResponse",
    "RoleAssignmentCreate",
    "RoleAssignmentListResponse",
    "RoleAssignmentRead",
    "RoleCreate",
    "RoleCreateLabels",
    "RoleListResponse",
    "RoleRead",
    "RoleReadLabels",
    "RoleUpdate",
    "RoleUpdateLabelsType0",
    "RuntimeSettingRead",
    "RuntimeSettingReadLabels",
    "RuntimeSettingReadValidationSchemaType0",
    "SettingBulkUpdateItem",
    "SettingBulkUpdateRequest",
    "SettingCategoryRead",
    "SettingsListResponse",
    "SettingUpdate",
    "SettingValueType",
    "SignalResponse",
    "SubResourceRoleAssignmentCreate",
    "TestExecutionCreate",
    "TestExecutionCreatePreResolvedNodes",
    "TestExecutionCreateTriggerInputs",
    "ToolBulkUpdate",
    "ToolExecution",
    "ToolExecutionInputParameters",
    "ToolExecutionLabels",
    "ToolExecutionListResponse",
    "ToolExecutionOutputDataType0",
    "ToolExecutionStatus",
    "ToolListResponse",
    "ToolMetricsToolSummary",
    "ToolMetricsToolSummaryListResponse",
    "ToolParameter",
    "ToolParameterDefaultValueType0",
    "ToolParameterExampleValueType0",
    "ToolParameterLabels",
    "ToolParameterType",
    "ToolProviderCreate",
    "ToolProviderListResponse",
    "ToolProviderPatch",
    "ToolProviderRefreshResult",
    "ToolProviderValidationResult",
    "ToolProviderWithConfiguration",
    "ToolProviderWithConfigurationLabels",
    "ToolStatus",
    "ToolUpdate",
    "ToolWithParameters",
    "ToolWithParametersLabels",
    "UpdateExampleRequest",
    "UploadFilesBody",
    "UserCreate",
    "UserDirectoryEntry",
    "UserGroupRead",
    "UserGroupReadLabels",
    "UserGroupsSet",
    "UserIdentityAttach",
    "UserIdentityListResponse",
    "UserIdentityRead",
    "UserInfo",
    "UserRead",
    "UserReference",
    "UserUpdate",
    "ValidateNameResourceType",
    "ValidateNameResponse",
    "WebhookResponse",
    "WhatCanIResponse",
    "WhoCanRequest",
    "WhoCanRequestResourceLabels",
    "WhoCanRequestResourceMetadata",
    "WhoCanResponse",
    "WhoCanUser",
    "WorkflowContext",
    "WorkflowContextInputs",
    "WorkflowCreate",
    "WorkflowCreateLabels",
    "WorkflowDefinition",
    "WorkflowDefinitionEdgesItem",
    "WorkflowDefinitionNodesItem",
    "WorkflowDefinitionTriggersItem",
    "WorkflowListResponse",
    "WorkflowRead",
    "WorkflowReadLabels",
    "WorkflowReadWithVersion",
    "WorkflowReadWithVersionLabels",
    "WorkflowUpdate",
    "WorkflowUpdateLabelsType0",
    "WorkflowVersionListResponse",
    "WorkflowVersionRead",
    "WorkflowVersionReadWorkflowDefinition",
    "WorkflowVersionStatus",
)

_MODEL_MODULES = frozenset(path.stem for path in Path(__file__).parent.glob("*.py") if path.stem != "__init__")


def _class_name_to_module(name: str) -> str:
    module_name = re.sub(r"[-\s]+", "_", name)
    module_name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", module_name)
    module_name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", module_name)
    return module_name.lower()


def __getattr__(name: str) -> Any:
    module_name = _class_name_to_module(name)
    if module_name not in _MODEL_MODULES:
        msg = f"module {__name__!r} has no attribute {name!r}"
        raise AttributeError(msg)

    module = importlib.import_module(f"{__name__}.{module_name}")
    try:
        value = getattr(module, name)
    except AttributeError as exc:
        msg = f"module {module.__name__!r} has no attribute {name!r}"
        raise AttributeError(msg) from exc

    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
