import type * as IntegrationsAPI from '@ansible/nexus-contracts/src/integrations-api.js'

import { mockDate } from './mockDates'

type IntegrationRead = IntegrationsAPI.components['schemas']['IntegrationRead']

export const integrations: IntegrationRead[] = [
  {
    id: '1',
    name: 'GitHub Copilot',
    description: 'GitHub Copilot MCP integration',
    integration_type: 'mcp_server',
    enabled: true,
    validation_status: 'available',
    scope: 'global',
    configuration: { integration_type: 'mcp_server', base_url: 'https://mcp.github.com' },
    management_credential_id: null,
    last_validated_at: '2024-01-15T10:00:00Z',
    validation_error: null,
    refresh_status: 'available',
    last_refreshed_at: '2024-01-15T10:00:00Z',
    refresh_error: null,
    total_tool_count: 5,
    enabled_tool_count: 5,
    total_model_count: 0,
    enabled_model_count: 0,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
    created_by: 'user-1',
    labels: {},
  },
  {
    id: '2',
    name: 'Slack Bot',
    description: 'Slack messaging integration',
    integration_type: 'mcp_server',
    enabled: true,
    validation_status: 'available',
    scope: 'global',
    configuration: { integration_type: 'mcp_server', base_url: 'https://mcp.slack.com' },
    management_credential_id: null,
    last_validated_at: '2024-01-16T11:00:00Z',
    validation_error: null,
    refresh_status: 'available',
    last_refreshed_at: '2024-01-16T11:00:00Z',
    refresh_error: null,
    total_tool_count: 3,
    enabled_tool_count: 3,
    total_model_count: 0,
    enabled_model_count: 0,
    created_at: '2024-01-16T11:00:00Z',
    updated_at: '2024-01-16T11:00:00Z',
    created_by: 'user-1',
    labels: {},
  },
  {
    id: '3',
    name: 'Jira Integration',
    description: 'Jira project tracking',
    integration_type: 'mcp_server',
    enabled: true,
    validation_status: 'error',
    scope: 'global',
    configuration: { integration_type: 'mcp_server', base_url: 'https://mcp.atlassian.com' },
    management_credential_id: null,
    last_validated_at: '2024-01-17T12:00:00Z',
    validation_error: 'Connection refused',
    refresh_status: 'error',
    last_refreshed_at: '2024-01-17T12:00:00Z',
    refresh_error: 'Unable to connect to service',
    total_tool_count: 3,
    enabled_tool_count: 2,
    total_model_count: 0,
    enabled_model_count: 0,
    created_at: '2024-01-17T12:00:00Z',
    updated_at: '2024-01-17T12:00:00Z',
    created_by: 'user-1',
    labels: {},
  },
  {
    id: '4',
    name: 'ServiceNow',
    description: 'ServiceNow ITSM integration',
    integration_type: 'mcp_server',
    enabled: true,
    validation_status: 'unknown',
    scope: 'global',
    configuration: { integration_type: 'mcp_server', base_url: 'https://mcp.servicenow.com' },
    management_credential_id: null,
    last_validated_at: null,
    validation_error: null,
    refresh_status: null,
    last_refreshed_at: null,
    refresh_error: null,
    total_tool_count: 0,
    enabled_tool_count: 0,
    total_model_count: 0,
    enabled_model_count: 0,
    created_at: '2024-01-18T13:00:00Z',
    updated_at: '2024-01-18T13:00:00Z',
    created_by: 'user-1',
    labels: {},
  },
  {
    id: '5',
    name: 'PagerDuty',
    description: 'PagerDuty incident management',
    integration_type: 'mcp_server',
    enabled: false,
    validation_status: 'available',
    scope: 'global',
    configuration: { integration_type: 'mcp_server', base_url: 'https://mcp.pagerduty.com' },
    management_credential_id: null,
    last_validated_at: '2024-01-19T14:00:00Z',
    validation_error: null,
    refresh_status: 'available',
    last_refreshed_at: '2024-01-19T14:00:00Z',
    refresh_error: null,
    total_tool_count: 1,
    enabled_tool_count: 1,
    total_model_count: 0,
    enabled_model_count: 0,
    created_at: '2024-01-19T14:00:00Z',
    updated_at: '2024-01-19T14:00:00Z',
    created_by: 'user-1',
    labels: {},
  },
  {
    id: '10',
    name: 'Red Hat AI',
    description: 'Red Hat AI LLM provider for Granite models',
    integration_type: 'llm_provider',
    enabled: true,
    validation_status: 'available',
    scope: 'global',
    configuration: {
      integration_type: 'llm_provider',
      provider_hint: 'red_hat_ai',
      base_url: 'https://api.redhat.ai/v1',
    },
    management_credential_id: null,
    last_validated_at: mockDate.daysAgo3,
    validation_error: null,
    refresh_status: 'available',
    last_refreshed_at: mockDate.daysAgo1,
    refresh_error: null,
    total_tool_count: 0,
    enabled_tool_count: 0,
    total_model_count: 5,
    enabled_model_count: 3,
    created_at: mockDate.daysAgo5,
    updated_at: mockDate.daysAgo1,
    created_by: 'user-1',
    labels: {},
  },
  {
    id: '11',
    name: 'OpenAI Production',
    description: 'OpenAI API for production workloads',
    integration_type: 'llm_provider',
    enabled: true,
    validation_status: 'available',
    scope: 'global',
    configuration: {
      integration_type: 'llm_provider',
      provider_hint: 'openai',
      base_url: 'https://api.openai.com/v1',
    },
    management_credential_id: null,
    last_validated_at: mockDate.daysAgo2,
    validation_error: null,
    refresh_status: 'available',
    last_refreshed_at: mockDate.daysAgo1,
    refresh_error: null,
    total_tool_count: 0,
    enabled_tool_count: 0,
    total_model_count: 8,
    enabled_model_count: 4,
    created_at: mockDate.daysAgo4,
    updated_at: mockDate.daysAgo1,
    created_by: 'user-1',
    labels: {},
  },
]
