import { Compass, CompassContent } from '@patternfly/react-core'
import { QueryClientProvider } from '@tanstack/react-query'

import { SessionTimeoutWarning } from '../components/session/SessionTimeoutWarning'
import { AlertProvider } from '../providers/alerts'
import { ColorSchemeProvider } from '../providers/theme/ColorSchemeProvider'
import { UnsavedChangesProvider } from '../providers/unsaved-changes/UnsavedChangesProvider'
import { queryClient } from '../queryClient'
import { TestSignInCallback } from '../routes/access-management/authentication/identity-providers/TestSignInCallback'
import { DocLinkProvider } from '../utils/docs/DocLinkProvider'

import { AppDockedNav } from './AppDockedNav'
import { AppLogin } from './AppLogin'
import { AppRoute } from './AppRoute'
import { AppRouter } from './AppRouter'

export default function App() {
  // Handle test-signin callback before auth — the popup doesn't need a full session.
  // A cryptographic nonce generated by the opener is verified before processing claims,
  // preventing cross-window data injection.
  if (globalThis.location.pathname === AppRoute.Auth.TestSignInCallback) {
    return <TestSignInCallback />
  }

  return (
    <QueryClientProvider client={queryClient}>
      <DocLinkProvider>
        <ColorSchemeProvider>
          <AlertProvider>
            <UnsavedChangesProvider>
              <AppLogin>
                <SessionTimeoutWarning />
                <Compass
                  className="pf-m-no-screen-warning bg-deep-space"
                  dock={<AppDockedNav />}
                  main={
                    <CompassContent role="main">
                      <AppRouter />
                    </CompassContent>
                  }
                />
              </AppLogin>
            </UnsavedChangesProvider>
          </AlertProvider>
        </ColorSchemeProvider>
      </DocLinkProvider>
    </QueryClientProvider>
  )
}
