import { QueryClientProvider } from '@tanstack/react-query'
import { RouterProvider } from '@tanstack/react-router'

import { AlertProvider } from '../providers/alerts'
import { ColorSchemeProvider } from '../providers/theme/ColorSchemeProvider'
import { queryClient } from '../queryClient'
import { TestSignInCallback } from '../routes/access-management/authentication/identity-providers/TestSignInCallback'
import { DocLinkProvider } from '../utils/docs/DocLinkProvider'

import { AppRoute } from './AppRoute'
import { tanstackRouter } from './tanstackRouter'

export default function App() {
  // Handle test-signin callback before auth — the popup doesn't need a full session.
  // A cryptographic nonce generated by the opener is verified before processing claims,
  // preventing cross-window data injection.
  if (globalThis.location.pathname === AppRoute.Auth.TestSignInCallback) {
    return <TestSignInCallback />
  }

  return (
    <QueryClientProvider client={queryClient}>
      <DocLinkProvider>
        <ColorSchemeProvider>
          <AlertProvider>
            <RouterProvider router={tanstackRouter} />
          </AlertProvider>
        </ColorSchemeProvider>
      </DocLinkProvider>
    </QueryClientProvider>
  )
}
