---
name: SAST Snyk Code (Frontend)

on:
  schedule:
    - cron: '23 14 * * *'
  push:
    branches:
      - 'devel'
    paths:
      - 'frontend/**'
      - '.github/workflows/sast-snyk-frontend.yml'
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: snyk/actions/setup@9adf32b1121593767fc3c057af55b55db032dc04 # v1

      - name: Generate code vulnerability report
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk code test --project-name="${{ github.repository }}" --report ${{ github.workspace }}/frontend
        continue-on-error: true
