/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/activity_types': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List available activity types
     * @description Retrieve all available activity executor types that can be used in workflow definitions.
     *     This endpoint is used for workflow validation, UI tooling, and documentation.
     */
    get: operations['list_activity_types']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * Activity Type
     * @description Definition of an available activity executor type with its configuration schema
     */
    ActivityType: {
      /**
       * @description Unique identifier for the executor type
       * @example agentic
       * @enum {string}
       */
      type: 'agentic' | 'connector' | 'script' | 'api' | 'approval'
      /**
       * @description Human-readable name of the executor type
       * @example Agentic Tool Execution
       */
      name: string
      /**
       * @description Detailed description of what this executor type does
       * @example Execute tasks using external agentic tool servers (MCP) with AI model integration
       */
      description: string
      /**
       * @description JSON Schema defining the valid configuration structure for this executor type
       * @example {
       *       "type": "object",
       *       "required": [
       *         "agent",
       *         "tools",
       *         "model"
       *       ],
       *       "properties": {
       *         "agent": {
       *           "type": "string",
       *           "description": "MCP server URI",
       *           "pattern": "^mcp://.+"
       *         },
       *         "tools": {
       *           "type": "array",
       *           "description": "List of tool names to invoke",
       *           "items": {
       *             "type": "string"
       *           }
       *         },
       *         "model": {
       *           "type": "string",
       *           "description": "AI model to use",
       *           "enum": [
       *             "claude-3-opus",
       *             "claude-3-sonnet",
       *             "gpt-4",
       *             "gpt-4-turbo"
       *           ]
       *         }
       *       }
       *     }
       */
      config_schema: Record<string, never>
      /**
       * @description Example configurations for this executor type
       * @example [
       *       {
       *         "name": "Sentiment Analysis",
       *         "description": "Analyze text sentiment using MCP tool",
       *         "config": {
       *           "agent": "mcp://sentiment-server",
       *           "tools": [
       *             "analyze_sentiment"
       *           ],
       *           "model": "claude-3-opus",
       *           "prompt": "Analyze the sentiment of the following text"
       *         }
       *       }
       *     ]
       */
      examples?: {
        /** @description Name of the example */
        name?: string
        /** @description What this example demonstrates */
        description?: string
        /** @description Example configuration object */
        config?: Record<string, never>
      }[]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_activity_types: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of available activity types with their configuration schemas */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            activity_types?: components['schemas']['ActivityType'][]
          }
        }
      }
    }
  }
}
